------------------------------------------------------------------------------
--?NOMBRE DE SCRIPT....:?CTRTGMAEWU
--?DESCRIPCIÓN.........:?TRIGGER DE ACTUALIZACIÓN EN WWWFFMAESE
--?TIPO OBJETO.........:?TRIGGER.
--?REQUERIMIENTO.......:?PMO32277-MODERNIZACION ISERIES.
--?SUBDOMINIO..........:?TRANSVERSALES DE APOYO ISERIES.
--?FECHA DE CREACIÓN...:?OCTUBRE  09 -2021.
--?AUTOR...............:?IBM - MAURICIO ATEHORTUA
--?
------------------------------------------------------------------------------
--CREATE OR REPLACE TABLE &LIB/SEGFFMAESW
CREATE OR REPLACE TABLE SEGLIBRAMD.SEGFFMAESW (
	CANAL CHAR(3) CCSID 284 NOT NULL DEFAULT '' ,
	IDSESION CHAR(60) CCSID 284 NOT NULL DEFAULT '' ,
	ESTADOSESI CHAR(1) CCSID 284 NOT NULL DEFAULT '' ,
	TIEMPOSESI NUMERIC(10, 0) NOT NULL DEFAULT 0 ,
	CAMPOUSUA1 CHAR(40) CCSID 284 NOT NULL DEFAULT '' ,
	CAMPOUSUA2 CHAR(40) CCSID 284 NOT NULL DEFAULT '' ,
	CAMPOUSUA3 NUMERIC(10, 0) NOT NULL DEFAULT 0 ,
	INSERT_TIMESTAMP FOR COLUMN INSTIME
TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	UPDATE_TIMESTAMP FOR COLUMN UPDTIME
TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON
UPDATE AS ROW CHANGE TIMESTAMP NOT NULL ,
CONSTRAINT SEGLIBRAMD.Q_SEGLIBRAMD_SEGFFMAESW_CANAL_00001
PRIMARY KEY( CANAL , IDSESION , INSERT_TIMESTAMP ) )
	
	RCDFMT RFFMAES    ;

LABEL ON TABLE SEGLIBRAMD.SEGFFMAESW
	IS 'Tabla Maestro de Sesiones WWW' ;

LABEL ON COLUMN SEGLIBRAMD.SEGFFMAESW
( CANAL IS 'Id del canal' ,
	IDSESION IS 'Identificados       de sesión' ,
	ESTADOSESI IS 'Estado              de sesión' ,
	TIEMPOSESI IS 'Milisegundos        sesión' ,
	CAMPOUSUA1 IS 'Campo libre 1' ,
	CAMPOUSUA2 IS 'Campo libre 2' ,
	CAMPOUSUA3 IS 'Campo libre 3' ) ;

LABEL ON COLUMN SEGLIBRAMD.SEGFFMAESW
( CANAL TEXT IS 'Id canal' ,
	IDSESION TEXT IS 'Identificados de sesión' ,
	ESTADOSESI TEXT IS 'Estado de sesión' ,
	TIEMPOSESI TEXT IS 'Tiempo milisegundos sesión' ,
	CAMPOUSUA1 TEXT IS 'Campo libre 1' ,
	CAMPOUSUA2 TEXT IS 'Campo libre 2' ,
	CAMPOUSUA3 TEXT IS 'Campo libre 3' ) ;
	
