Create Table &LIB/SEGFFAUT15
(TDOUBLE    DOUBLE            NOT NULL DEFAULT
 ,TCHAR           CHAR (50)     NOT NULL DEFAULT ''
 ,TCHAR2          CHAR (300) CCSID 284 NOT NULL WITH DEFAULT ''
 ,TVARCHAR1       VARCHAR (50)
 ,TVARCHAR2       VARCHAR (50)

) RcdFmt SEG15R;

Label On Table &LIB/SEGFFAUT15 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT15
(TDOUBLE    TEXT IS 'TDOUBLE'
,TCHAR            TEXT IS 'CHAR'
,TCHAR2           TEXT IS 'CHAR'
,TVARCHAR1        TEXT IS 'VARCHAR1'
,TVARCHAR2        TEXT IS 'VARCHAR2'
 );

Label On Column &LIB/SEGFFAUT15
(TDOUBLE         Is 'T_DOUBLE'
,TCHAR                 IS 'T_CHAR'
,TCHAR2                IS 'T_TCHAR2'
,TVARCHAR1             IS 'T_VARCHAR1'
,TVARCHAR2             IS 'T_VARCHAR2'
 );
