CREATE TABLE &LIB/SEGFFHSRCS (
Journal      Char       (10)    ,
Libjrn       char       (10)    ,
Receptor     Char       (10)    ,
Librcv       char       (10)    ,
FechCon      date               ,
HoraCrea     time               ,
FechSalv     date               ,
FechElim     TimeStamp          ,
FechRest     char       (8 )    ,
HoraRest     char       (8 )    ,
Tamano       char       (10)    ,
cmdsal       char       (10)    ,
dispos       char       (10)    ,
vol1         char       (10)    ,
vol2         char       (10)    ,
vol3         char       (10)    ,
vol4         char       (10)    ,
vol5         char       (10)    ,
vol6         char       (10)    ,
vol7         char       (10)    ,
vol8         char       (10)    ,
vol9         char       (10)    ,
vol10        char       (10)    ,
masvol       char       (1 )    ,
numseq       char       (4 )    ,
nomsavF      char       (10)    ,
libsavF      char       (10)    ,
etiqueta     char       (17)     )

RCDFMT   REGHSRCV;

LABEL ON TABLE &LIB/SEGFFHSRCS  Is
'Regitro de receptores depurados';

LABEL ON &LIB/SEGFFHSRCS (
Journal       Text Is  'Journal',
Libjrn        Text Is  'Lib Jrn',
Receptor      Text Is  'Receptor',
Librcv        Text is  'Lib Rcv',
FechCon       Text Is  'Fecha conexión',
HoraCrea      Text Is  'Hora Creación',
FechSalv      Text Is  'Fecha salvado',
FechElim      Text Is  'Fecha depuración',
FechRest      Text Is  'Fecha Restauración',
HoraRest      Text Is  'Hora Restauración',
Tamano        Text is  'Tamaño',
cmdsal        Text Is  'Cmd salvar',
dispos        Text Is  'Disp salvar',
vol1          Text Is  'Vol1 Salvado',
vol2          Text is  'Vol2 Salvado',
vol3          Text Is  'Vol3 Salvado',
vol4          Text Is  'Vol4 Salvado',
vol5          Text Is  'Vol5 Salvado',
vol6          Text Is  'Vol6 Salvado',
vol7          Text Is  'Vol7 Salvado',
vol8          Text Is  'Vol8 Salvado',
vol9          Text Is  'Vol9 Salvado',
vol10         Text Is  'Vol10 Salvado',
masvol        Text Is  'Mas vol',
numseq        Text Is  'Secuencia',
nomsavF       Text Is  'SavF',
libsavF       Text Is  'Lib SavF',
etiqueta      Text is  'Etiqueta');

LABEL ON COLUMN &LIB/SEGFFHSRCS (
Journal            Is  'Journal',
Libjrn             Is  'Lib Jrn',
Receptor           Is  'Receptor',
Librcv             is  'Lib Rcv',
FechCon            Is  'Fecha conexión',
HoraCrea           Is  'Hora Creación',
FechSalv           Is  'Fecha salvado',
FechElim           Is  'Fecha depuración',
FechRest           Is  'Fecha Restauración',
HoraRest           Is  'Hora Restauración',
Tamano             is  'Tamaño',
cmdsal             Is  'Cmd salvar',
dispos             Is  'Disp salvar',
vol1               Is  'Vol1 Salvado',
vol2               is  'Vol2 Salvado',
vol3               Is  'Vol3 Salvado',
vol4               Is  'Vol4 Salvado',
vol5               Is  'Vol5 Salvado',
vol6               Is  'Vol6 Salvado',
vol7               Is  'Vol7 Salvado',
vol8               Is  'Vol8 Salvado',
vol9               Is  'Vol9 Salvado',
vol10              Is  'Vol10 Salvado',
masvol             Is  'Mas vol',
numseq             Is  'Secuencia',
nomsavF            Is  'SavF',
libsavF            Is  'Lib SavF',
etiqueta           Is  'Etiqueta');
