Create Table &LIB/SEGFFAUT28
(TBINARY    BINARY   (115)    NOT NULL DEFAULT
,TVARBINARY VARBINARY(115)    NOT NULL DEFAULT
,TCHAR2     CHAR (300) CCSID 284 NOT NULL WITH DEFAULT ''
,TVARCHAR   VARCHAR (70)
) RcdFmt SEG28R;

Label On Table &LIB/SEGFFAUT28 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT28
(TBINARY    TEXT IS 'TBINARY'
,TVARBINARY TEXT IS 'TVARBINARY'
,TCHAR2     Text Is 'CHAR'
,TVARCHAR   Text Is 'VARCHAR'
 );

Label On Column &LIB/SEGFFAUT28
(TBINARY            Is 'T_BINARY'
,TVARBINARY         Is 'T_VARBINARY'
,TCHAR2             IS 'T_TCHAR2'
,TVARCHAR           IS 'T_VARCHAR'
 );

