Create OR REPLACE Table &LIB/SEGFFIFSPG (
 APLICATIVO        CHAR         (3)   NOT NULL DEFAULT '' ,
 PROCESO           CHAR        (10)   NOT NULL DEFAULT '' ,
 ESTADO            CHAR         (1)   NOT NULL DEFAULT '' ,
 CODFREQ           CHAR         (1)   NOT NULL DEFAULT '' ,
 DIAFREQ           CHAR         (4)   NOT NULL DEFAULT '' ,
 HORADEP           NUMERIC      (4,2)   NOT NULL DEFAULT 0 ,
 TIPODEP           CHAR         (1)   NOT NULL DEFAULT '' ,
 IFSDEP            CHAR         (250) NOT NULL DEFAULT '' ,
 FECCRE            TIMESTAMP          NOT NULL DEFAULT CURRENT TIMESTAMP,
 USUCRE            CHAR         (10)  NOT NULL DEFAULT '' ,
 FECMOD            TIMESTAMP          NOT NULL DEFAULT CURRENT TIMESTAMP,
 USUMOD            CHAR         (10)  NOT NULL DEFAULT '' ,
 FECDEP            TIMESTAMP          NOT NULL DEFAULT CURRENT TIMESTAMP,
 PRCEXT            CHAR          (1)  NOT NULL DEFAULT '' ,
 DLCACO            CHAR (1)           NOT NULL DEFAULT '' ,
 INCPRO            CHAR (1)           NOT NULL DEFAULT '' ,
 TIPSQN            NUMERIC     (4,0)  NOT NULL DEFAULT 0 ,
 CANDIG            NUMERIC     (1,0)  NOT NULL DEFAULT 0 ,
 NDESDE            NUMERIC     (8,0)  NOT NULL DEFAULT 0 ,
 NHASTA            NUMERIC     (8,0)  NOT NULL DEFAULT 0 ,
 FECSIG            NUMERIC     (8,0)  NOT NULL DEFAULT 0 ,
 VALCAL            CHAR         (1)   NOT NULL DEFAULT '',
 SALVAR            CHAR         (1)   NOT NULL DEFAULT '',
 Constraint SEGFFIFSPG_PK Primary Key(APLICATIVO, PROCESO)
) RcdFmt @RIFSPG;

Label On Table &LIB/SEGFFIFSPG Is 'Tabla de depuracion de Rutas IFS    ';

Label On  &LIB/SEGFFIFSPG
(APLICATIVO    Text Is 'Código Aplicativo' ,
 PROCESO       Text Is 'Id proceso' ,
 ESTADO        Text Is 'Estado registro' ,
 CODFREQ       Text Is 'Codigo frencuencia' ,
 DIAFREQ       Text Is 'Dia frecuencia' ,
 HORADEP       Text Is 'Hora depuración' ,
 TIPODEP       Text Is 'Tipo depuracion',
 IFSDEP        Text Is 'Ruta IFS',
 FECCRE        Text Is 'Fecha/hora creación',
 USUCRE        Text Is 'Usuario creación',
 FECMOD        Text Is 'Fecha/hora modificación',
 USUMOD        Text Is 'Usuario modificación',
 FECDEP        Text Is 'Fecha/Hora Depuración',
 PRCEXT        Text Is 'Proceso Extemporáneo',
 DLCACO        Text Is 'Borra carpeta completa',
 INCPRO        Text Is 'Inactivar al procesar',
 TIPSQN        Text Is 'Tipo de Secuencia',
 CANDIG        Text Is 'Cantidad de Digitos',
 NDESDE        Text Is 'Número Desde',
 NHASTA        Text Is 'Número Hasta',
 FECSIG        Text Is 'Fecha Siguiente',
 VALCAL        Text Is 'Valida Calendario',
 SALVAR        Text Is 'Salvar Rutas'
 );
Label On Column  &LIB/SEGFFIFSPG
(APLICATIVO    Is     'Código              Aplicativo' ,
 PROCESO       Is     'Id                  proceso' ,
 ESTADO        Is     'Estado              registro' ,
 CODFREQ       Is     'Codigo              frencuencia' ,
 DIAFREQ       Is     'Dia                 frecuencia' ,
 HORADEP       Is     'Hora                depuración' ,
 TIPODEP       Is     'Tipo                depuracion',
 IFSDEP        Is     'Ruta                IFS',
 FECCRE        Is     'Fecha/hora          creación',
 USUCRE        Is     'Usuario             creación',
 FECMOD        Is     'Fecha/hora          modificación',
 USUMOD        Is     'Usuario             modificación',
 FECDEP        Is     'Fecha/Hora          Depuración',
 PRCEXT        Is     'Proceso             Extemporáneo',
 DLCACO        Is     'Borra carpeta       completa',
 INCPRO        Is     'Inactivar           al procesar',
 TIPSQN        Is     'Tipo de             Secuencia',
 CANDIG        Is     'Cantidad de         Digitos',
 NDESDE        Is     'Número              Desde',
 NHASTA        Is     'Número              Hasta',
 FECSIG        Is     'Fecha               Siguiente',
 VALCAL        Is     'Valida              Calendario',
 SALVAR        IS     'Salvar Rutas'
 );
