Create Table &LIB/SEGFFAUT04
(TDATE        DATE      NOT NULL WITH DEFAULT
,TTIME        TIME  NOT NULL WITH DEFAULT
,TTIMESTAMP   TIMESTAMP    NOT NULL DEFAULT CURRENT TIMESTAMP
,TGRAPHIC    GRAPHIC   (115)    NOT NULL DEFAULT
,TVARGRAPHIC VARGRAPHIC(115)    NOT NULL DEFAULT
) RcdFmt SEG04R;

Label On Table &LIB/SEGFFAUT04 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT04
(TDATE         TEXT IS 'TDATE     '
,TTIME            TEXT IS 'TIME'
,TTIMESTAMP       TEXT IS 'TTIMESTAMP'
,TGRAPHIC    TEXT IS 'TGRAPHIC'
,TVARGRAPHIC TEXT IS 'TVARGRAPHIC'
 );

Label On Column &LIB/SEGFFAUT04
(TDATE              Is 'T_DATE    '
,TTIME                 IS 'T_TIME    '
,TTIMESTAMP            IS 'T_TIMESTAMP'
,TGRAPHIC              IS 'T_GRAPHIC'
,TVARGRAPHIC           IS 'T_VARGRAPHIC'

 );
