--AW1192003_BC_1:"RUNSQLSTM SRCFILE(R1EDM/EDMSRC) SRCMBR(EDMFFSPIFS) "
--AW1192003_BC_2:"COMMIT(*NONE)"
--AW1192003_OBJTYPE:"*FILE"
CREATE OR REPLACE TABLE &LIB/SEGFFATAUT (
LIBOBJ       CHAR       (10)   ,
OBJETO       CHAR       (10)   ,
TIPOBJ       CHAR       (7)    ,
USRAUT       CHAR       (10)   ,
JOB          CHAR       (10)   ,
USRJOB       CHAR       (10)   ,
NUMJOB       CHAR       (6)    ,
ESTADO       CHAR       (1)    ,
MSGID        CHAR       (7)    ,
CONSTRAINT PK_ATAUT PRIMARY KEY (OBJETO, LIBOBJ,TIPOBJ,USRAUT))
RCDFMT   REGATAUT;

LABEL ON TABLE &LIB/SEGFFATAUT  Is
'REGISTRA AUTORIZACIONES';

LABEL ON &LIB/SEGFFATAUT (
OBJETO        Text Is  'OBJETO',
LIBOBJ        Text Is  'LIBRERIA',
TIPOBJ        TEXT IS  'TIPO OBJETO',
USRAUT        Text Is  'USUARIO AUTORIZADO',
JOB           TEXT IS  'TRABAJO',
USRJOB        TEXT IS  'USUARIO',
NUMJOB        Text Is  'NUMERO',
ESTADO        TEXT IS  'ESTADO');

LABEL ON COLUMN &LIB/SEGFFATAUT (
OBJETO             IS  'OBJETO',
LIBOBJ             IS  'LIBRERIA',
TIPOBJ             IS  'TIPO OBJETO',
USRAUT             IS  'USUARIO AUTORIZADO',
JOB                IS  'TRABAJO',
USRJOB             IS  'USUARIO',
NUMJOB             IS  'NUMERO',
ESTADO             IS  'ESTADO');
