Create Table &LIB/SEGFFAUT18
(TDATALINK         DATALINK   (300)  LINKTYPE URL NO LINK CONTROL NOT NULL WITH
 DEFAULT
) RcdFmt SEG18R;

Label On Table &LIB/SEGFFAUT18 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT18
(TDATALINK    TEXT IS 'TDATALINK'
 );

Label On Column &LIB/SEGFFAUT18
(TDATALINK         Is 'T_DATALINK'
 );
