Create Table &LIB/SEGFFAUT10
(TNUMERIC        NUMERIC (20)  NOT NULL WITH DEFAULT
,TNUMERICD       NUMERIC (15,4)  NOT NULL WITH DEFAULT
,TCHAR           CHAR (50)     NOT NULL DEFAULT ''
,TCHAR2          CHAR (300) CCSID 284 NOT NULL WITH DEFAULT ''
,TVARCHAR        VARCHAR (70)
) RcdFmt SEG10R;

Label On Table &LIB/SEGFFAUT10 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT10
(TNUMERIC         TEXT IS 'TNUMERIC     '
,TNUMERICD        TEXT IS 'TNUMERIC DEC '
,TCHAR            TEXT IS 'CHAR'
,TCHAR2           TEXT IS 'CHAR'
,TVARCHAR         TEXT IS 'VARCHAR'

 );

Label On Column &LIB/SEGFFAUT10
(TNUMERIC              Is 'T_NUMERIC    '
,TNUMERICD             Is 'T_NUMERIC DEC'
,TCHAR                 IS 'T_CHAR'
,TCHAR2                IS 'T_TCHAR2'
,TVARCHAR              IS 'T_VARCHAR'
 );
