/*
 * ***********************************************************************
 * NOMBRE DE CROGRAMA..: SEGFFLGDBL                                      *
 * DESCRIPCIÓN.........: ARCHIVO HISTORICO DE CONTROL NOVEDADES DE       *
 *                       DESBLOQUEO AUTOMATICO USUARIOS ISERIES          *
 * REQUERIMIENTO.......: PMO25818 - IEX_DESBLOQUEO USUARIOS ISERIES      *
 * SUBDOMINIO..........: RIESGOS Y SEGURIDAD                             *
 * FECHA DE CREACIÓN...: 19 DE JUNIO DE 2018.                            *
 * AUTOR...............: ALEXANDER OLARTE MU#OZ.                         *
 * ***********************************************************************
 *- REGISTRO Y CAMPOS ------------------------------------------
*/
CREATE TABLE   &LIB/SEGFFLGDBL(
   USUARIO     CHAR (10)   NOT NULL DEFAULT '' ,
   FECHFASE1   NUMERIC(8)  NOT NULL DEFAULT 0  ,
   HORAFASE1   NUMERIC(6)  NOT NULL DEFAULT 0  ,
   FECHFASE2   NUMERIC(8)  NOT NULL DEFAULT 0  ,
   HORAFASE2   NUMERIC(6)  NOT NULL DEFAULT 0  ,
   FECHFASE3   NUMERIC(8)  NOT NULL DEFAULT 0  ,
   HORAFASE3   NUMERIC(6)  NOT NULL DEFAULT 0  ,
   ESTADO      NUMERIC(1)  NOT NULL DEFAULT 0  ,
   FECHMODIF   NUMERIC(8)  NOT NULL DEFAULT 0  ,
   HORAMODIF   NUMERIC(6)  NOT NULL DEFAULT 0
)
RCDFMT REGDBLUSU;

/* DESCRIPCIÓN */
LABEL ON TABLE &LIB/SEGFFLGDBL IS
'Archivo Log Desbloqueo Automatico de Usuarios';

/* DESCRIPCIÓN CAMPOS */
LABEL ON &LIB/SEGFFLGDBL
(USUARIO     TEXT IS  'PERFIL DE USUARIO',
 FECHFASE1   TEXT IS  'FECHA DE FASE 1',
 HORAFASE1   TEXT IS  'HORA DE FASE 1',
 FECHFASE2   TEXT IS  'FECHA DE FASE 2',
 HORAFASE2   TEXT IS  'HORA DE FASE 2',
 FECHFASE3   TEXT IS  'FECHA DE FASE 3',
 HORAFASE3   TEXT IS  'HORA DE FASE 3',
 ESTADO      TEXT IS  'ESTADO/FASE ACTUAL',
 FECHMODIF   TEXT IS  'FECHA MODIFICACION',
 HORAMODIF   TEXT IS  'HORA MODIFICACION'
);

/* DESCRIPCIÓN CAMPOS */
LABEL ON COLUMN &LIB/SEGFFLGDBL
(USUARIO          IS  'PERFIL_USUARIO',
 FECHFASE1        IS  'FECHA_FASE1',
 HORAFASE1        IS  'HORA_FASE1',
 FECHFASE2        IS  'FECHA_FASE2',
 HORAFASE2        IS  'HORA_FASE2',
 FECHFASE3        IS  'FECHA_FASE3',
 HORAFASE3        IS  'HORA_FASE3',
 ESTADO           IS  'ESTADO_ACTUAL',
 FECHMODIF        IS  'FECHA_MODIF',
 HORAMODIF        IS  'HORA_MODIF'
);
