Create Table &LIB/SEGFFAUT35
(TXML         XML        NOT NULL WITH DEFAULT
,TTIMESTAMP   TIMESTAMP    NOT NULL DEFAULT CURRENT TIMESTAMP
,TTIME        TIME  NOT NULL WITH DEFAULT
,TDATE        DATE      NOT NULL WITH DEFAULT
) RcdFmt SEG35R;

Label On Table &LIB/SEGFFAUT35 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT35
(TXML    TEXT IS 'TXML'
,TTIMESTAMP       TEXT IS 'TTIMESTAMP'
,TTIME            TEXT IS 'TIME      '
,TDATE            TEXT IS 'TDATE     '
 );

Label On Column &LIB/SEGFFAUT35
(TXML         Is 'T_XML'
,TTIMESTAMP            IS 'T_TIMESTAMP'
,TTIME                 IS 'T_TIME    '
,TDATE                 IS 'T_DATE    '
 );
