Create Table &LIB/SEGFFAUT21
(TTIMESTAMP   TIMESTAMP    NOT NULL DEFAULT CURRENT TIMESTAMP
,TTIME        TIME  NOT NULL WITH DEFAULT
,TDATE        DATE      NOT NULL WITH DEFAULT
,TCHAR2       CHAR (300) CCSID 284 NOT NULL WITH DEFAULT ''
,TVARCHAR     VARCHAR (70)
) RcdFmt SEG21R;

Label On Table &LIB/SEGFFAUT21 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT21
(TTIMESTAMP    TEXT IS 'TTIMESTAMP'
,TTIME         TEXT IS 'TTIME     '
,TDATE         TEXT IS 'TDATE     '
,TCHAR2        TEXT IS 'CHAR'
,TVARCHAR      TEXT IS 'VARCHAR'
 );

Label On Column &LIB/SEGFFAUT21
(TTIMESTAMP         Is 'T_TIMESTAMP'
,TTIME              IS 'T_TIME    '
,TDATE              IS 'T_DATE    '
,TCHAR2             IS 'T_TCHAR2'
,TVARCHAR           IS 'T_VARCHAR'
 );
