Create Table &LIB/SEGFFAUT30
(TNUMERIC        NUMERIC (20) NOT NULL WITH DEFAULT
,TNUMERICD       NUMERIC (15,4)  NOT NULL WITH DEFAULT
,TCHAR           CHAR (50)     NOT NULL DEFAULT ''
,TCHAR2          CHAR (200) CCSID 284 NOT NULL WITH DEFAULT ''
,TVARCHAR        VARCHAR (50)
,TTIMESTAMP   TIMESTAMP    NOT NULL DEFAULT CURRENT TIMESTAMP
,TTIME        TIME  NOT NULL WITH DEFAULT
,TDATE        DATE      NOT NULL WITH DEFAULT

) RcdFmt SEG30R;

Label On Table &LIB/SEGFFAUT30 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT30
(TNUMERIC         TEXT IS 'TNUMERIC     '
,TNUMERICD        TEXT IS 'TNUMERIC DEC '
,TCHAR            TEXT IS 'CHAR'
,TCHAR2           TEXT IS 'CHAR2'
,TVARCHAR         TEXT IS 'VARCHAR'
,TTIMESTAMP       TEXT IS 'TTIMESTAMP'
,TTIME            TEXT IS 'TIME      '
,TDATE            TEXT IS 'TDATE     '
 );

Label On Column &LIB/SEGFFAUT30
(TNUMERIC              Is 'T_NUMERIC    '
,TNUMERICD             Is 'T_NUMERIC DEC'
,TCHAR                 IS 'T_CHAR'
,TCHAR2                IS 'T_TCHAR2'
,TVARCHAR              IS 'T_VARCHAR'
,TTIMESTAMP            IS 'T_TIMESTAMP'
,TTIME                 IS 'T_TIME    '
,TDATE                 IS 'T_DATE    '
 );
