DROP TABLE  &LIB/SEGFFAUTLO;

CREATE OR REPLACE TABLE &LIB/SEGFFAUTLO (
 OBJETOAUTL        CHAR        (10) NOT NULL DEFAULT '' ,
 LIBRERIA          CHAR        (10) NOT NULL DEFAULT '' ,
 PROPIETARI        CHAR        (10) NOT NULL DEFAULT '' ,
 USERAUTORI        CHAR        (10) NOT NULL DEFAULT '' ,
 TIPOAUTORI        CHAR        (10) NOT NULL DEFAULT '' ,
 FECHASYS          NUMERIC      (8),
 HORASYS           NUMERIC      (6),
 DESCRIP           VARCHAR     (80)
)
RCDFMT   RAUTLO;

LABEL ON TABLE &LIB/SEGFFAUTLO  Is
'LOG DE REGISTROS DE AUTL ERRADAS';

LABEL ON &LIB/SEGFFAUTLO (
OBJETOAUTL         TEXT IS  'OBJETO AUTLS',
LIBRERIA           TEXT IS  'BIBLIOTECA',
PROPIETARI         TEXT IS  'PROPIETARIO',
USERAUTORI         Text Is  'USUARIO AUTORIZADO',
TIPOAUTORI         TEXT IS  'TIPO AUTORIZACION',
FECHASYS           TEXT IS  'FECHA SISTEMA',
HORASYS            TEXT IS  'HORA SISTEMA',
DESCRIP            TEXT IS  'DESCRIPCION DEL LOG');


LABEL ON COLUMN &LIB/SEGFFAUTLO (
OBJETOAUTL              IS  'OBJETO AUTLS',
LIBRERIA                IS  'BIBLIOTECA',
PROPIETARI              IS  'PROPIETARIO',
USERAUTORI              IS  'USUARIO AUTORIZADO',
TIPOAUTORI              IS  'TIPO AUTORIZACION',
FECHASYS                IS  'FECHA SISTEMA',
HORASYS                 IS  'HORA  SISTEMA',
DESCRIP                 IS  'DESCRIPCION DEL LOG');
