CREATE OR REPLACE TABLE &LIB.SEGFFMAESP(

CANAL CHAR(3) DEFAULT '',
IDSESION CHAR(60) DEFAULT '',
ESTADOSESI CHAR(1) DEFAULT '',
TIEMPOSESI NUMERIC(10) DEFAULT 0,
CAMPOUSUA1 CHAR(40) DEFAULT '',
CAMPOUSUA2 CHAR(40) DEFAULT '',
CAMPOUSUA3 NUMERIC(10) DEFAULT 0,
INSERT_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
UPDATE_TIMESTAMP TIMESTAMP FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL);




