Create Table &LIB/SEGFFAUT23
(TREAL    REAL            NOT NULL DEFAULT
,TDOUBLE  DOUBLE          NOT NULL DEFAULT
,TCLOB    CLOB   (100)   NOT NULL DEFAULT
) RcdFmt SEG23R;

Label On Table &LIB/SEGFFAUT23 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT23
(TREAL    TEXT IS 'TREAL'
,TDOUBLE    TEXT IS 'TDOUBLE'
,TCLOB    TEXT IS 'TCLOB'
 );

Label On Column &LIB/SEGFFAUT23
(TREAL         Is 'T_REAL'
,TDOUBLE       IS 'T_DOUBLE'
,TCLOB         IS 'T_CLOB'
 );
