Create Table &LIB/SEGFFAUT34
(TDATE        DATE      NOT NULL WITH DEFAULT
,TTIME        TIME  NOT NULL WITH DEFAULT
,TTIMESTAMP   TIMESTAMP    NOT NULL DEFAULT CURRENT TIMESTAMP
,TCHAR1          CHAR (50)     NOT NULL DEFAULT ''
,TCHAR2          CHAR (50)     NOT NULL DEFAULT ''
,TCHAR3          CHAR (50)     NOT NULL DEFAULT ''
,TCHAR4          CHAR (50)     NOT NULL DEFAULT ''
,TVARCHAR1       VARCHAR (70)
,TVARCHAR2       VARCHAR (70)
,TGRAPHIC    GRAPHIC   (115)    NOT NULL DEFAULT
,TVARGRAPHIC VARGRAPHIC(115)    NOT NULL DEFAULT
) RcdFmt SEG34R;

Label On Table &LIB/SEGFFAUT34 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT34
(TDATE         TEXT IS 'TDATE     '
,TTIME            TEXT IS 'TIME'
,TTIMESTAMP       TEXT IS 'TTIMESTAMP'
,TCHAR1           TEXT IS 'TCHAR1    '
,TCHAR2           TEXT IS 'TCHAR2    '
,TCHAR3           TEXT IS 'TCHAR3    '
,TCHAR4           TEXT IS 'TCHAR4    '
,TVARCHAR1        TEXT IS 'TVARCHAR1 '
,TVARCHAR2        TEXT IS 'TVARCHAR2 '
,TGRAPHIC    TEXT IS 'TGRAPHIC'
,TVARGRAPHIC TEXT IS 'TVARGRAPHIC'
 );

Label On Column &LIB/SEGFFAUT34
(TDATE              Is 'T_DATE    '
,TTIME                 IS 'T_TIME    '
,TTIMESTAMP            IS 'T_TIMESTAMP'
,TCHAR1                IS 'T_CHAR1    '
,TCHAR2                IS 'T_CHAR2    '
,TCHAR3                IS 'T_CHAR3    '
,TCHAR4                IS 'T_CHAR4    '
,TVARCHAR1             IS 'T_VARCHAR1 '
,TVARCHAR2             IS 'T_VARCHAR2 '
,TGRAPHIC              IS 'T_GRAPHIC'
,TVARGRAPHIC           IS 'T_VARGRAPHIC'

 );

