/*
 * ***********************************************************************
 * NOMBRE DE CROGRAMA..: SEGFFCADBL                                      *
 * DESCRIPCIÓN.........: ARCHIVO DE CANDIDATOS A DESBLOQUEO AUTOMATICO   *
 * REQUERIMIENTO.......: PMO25818 - IEX_DESBLOQUEO USUARIOS ISERIES      *
 * SUBDOMINIO..........: RIESGOS Y SEGURIDAD                             *
 * FECHA DE CREACIÓN...: 19 DE JUNIO DE 2018.                            *
 * AUTOR...............: ALEXANDER OLARTE MU#OZ.                         *
 * ***********************************************************************
 *- REGISTRO Y CAMPOS ------------------------------------------
*/
CREATE TABLE   &LIB/SEGFFCADBL(
   USUARIO     CHAR (10)   NOT NULL DEFAULT '' ,
   NUM_IDENTI  CHAR (15)   NOT NULL DEFAULT '' ,
   FECHA_ACT   NUMERIC(8)  NOT NULL DEFAULT 0  ,
   HORA_ACT    NUMERIC(6)  NOT NULL DEFAULT 0  ,
   FECHULTUSO  NUMERIC(8)  NOT NULL DEFAULT 0  ,
   DIAS_BLQ    NUMERIC(4)  NOT NULL DEFAULT 0  ,
   TIPO_NOVED  CHAR (12)   NOT NULL DEFAULT '',
   ESTADO_ACT  NUMERIC(1)  NOT NULL DEFAULT 0
)
RCDFMT REGCADBL;

/* DESCRIPCIÓN */
LABEL ON TABLE &LIB/SEGFFCADBL IS
'Archivo de Candidatos a Desbloqueo Automático';

/* DESCRIPCIÓN CAMPOS */
LABEL ON &LIB/SEGFFCADBL
(USUARIO     TEXT IS  'PERFIL DE USUARIO',
 NUM_IDENTI  TEXT IS  'NUMERO DE IDENTIFIC',
 FECHA_ACT   TEXT IS  'FECHA ACTUAL',
 HORA_ACT    TEXT IS  'HORA ACTUAL',
 FECHULTUSO  TEXT IS  'FECHA DE ULTIMO USO',
 DIAS_BLQ    TEXT IS  'NRO DIAS BLOQUEADO',
 TIPO_NOVED  TEXT IS  'TIPO DE NOVEDAD',
 ESTADO_ACT  TEXT IS  'ESTADO ACTUAL'
);

/* DESCRIPCIÓN CAMPOS */
LABEL ON COLUMN &LIB/SEGFFCADBL
(USUARIO          IS  'PERFIL_USUARIO',
 NUM_IDENTI       IS  'NUM_IDENTIFIC',
 FECHA_ACT        IS  'FECHA_ACTUAL',
 HORA_ACT         IS  'HORA_ACTUAL',
 FECHULTUSO       IS  'FECHA_ULTIMO_USO',
 DIAS_BLQ         IS  'NRO_DIAS_BLOQ',
 TIPO_NOVED       IS  'TIPO_NOVEDAD',
 ESTADO_ACT       IS  'ESTADO_ACTUAL'
);
