--AW1192003_BC_1:"RUNSQLSTM SRCFILE(R1SEG/SEGSRC) SRCMBR(SEGFFLOGWO) "
--AW1192003_BC_2:"COMMIT(*NONE)"
--AW1192003_OBJTYPE:"*FILE"
CREATE OR REPLACE TABLE &LIB/SEGFFLOGWO (
WO           CHAR       (30)   ,
FECHORA      TIMESTAMP,
CONSTRAINT PK_ATWO PRIMARY KEY (WO))
RCDFMT   REGLOGWO;

LABEL ON TABLE &LIB/SEGFFLOGWO  Is
'LOG PROCESAMIENTO DE WO PROCESADAS';

LABEL ON &LIB/SEGFFLOGWO (
WO            TEXT IS  'WO',
FECHORA       TEXT IS  'FECHA');


LABEL ON COLUMN &LIB/SEGFFLOGWO (
WO                 IS  'WO',
FECHORA            IS  'FECHA');
