--AW1192003_BC_1:"RUNSQLSTM SRCFILE(R1SEG/SEGSRC) SRCMBR(SEGFFLOGAU) "
--AW1192003_BC_2:"COMMIT(*NONE)"
--AW1192003_OBJTYPE:"*FILE"
CREATE OR REPLACE TABLE &LIB/SEGFFLOGAU (
WO           CHAR       (30)   ,
LIBOBJ       CHAR       (10)   ,
OBJETO       CHAR       (10)   ,
TIPOBJ       CHAR       (7)    ,
AUTORIZ      CHAR       (10)   ,
USRAUT       CHAR       (10)   ,
ERROR        CHAR       (1)   ,
CODERR       CHAR       (7)   ,
DESCERROR    CHAR       (300)  ,
FECHORA      TIMESTAMP       )
RCDFMT   REGLOGUT;

LABEL ON TABLE &LIB/SEGFFLOGAU  Is
'LOG PROCESAMIENTO DE AUTORIZACIONES MASIVAS';

LABEL ON &LIB/SEGFFLOGAU (
WO            TEXT IS  'WO',
LIBOBJ        TEXT IS  'OBJETO',
OBJETO        TEXT IS  'LIBRERIA',
TIPOBJ        TEXT IS  'TIPO OBJETO',
AUTORIZ       TEXT IS  'TIPO AUTORIZACIÓN',
USRAUT        TEXT IS  'USUARIO AUTORIZADO',
ERROR         TEXT IS  'ERROR',
CODERR        TEXT IS  'CODIGO DE ERROR',
DESCERROR     TEXT IS  'DESCRIPCIÓN',
FECHORA       TEXT IS  'FECHA');


LABEL ON COLUMN &LIB/SEGFFLOGAU (
WO                 IS  'WO',
LIBOBJ             IS  'OBJETO',
OBJETO             IS  'LIBRERIA',
TIPOBJ             IS  'TIPO OBJETO',
AUTORIZ            IS  'TIPO AUTORIZACIÓN',
USRAUT             IS  'USUARIO AUTORIZADO',
ERROR              IS  'ERROR',
CODERR             IS  'CODIGO DE ERROR',
DESCERROR          IS  'DESCRIPCIÓN',
FECHORA            IS  'FECHA');
