Create Table &LIB/SEGFFAUT38
(TDEC       DEC  (8, 2)   NOT NULL DEFAULT 0
,TCHAR      CHAR (50)     NOT NULL DEFAULT ''
,TCHAR2     CHAR (300) CCSID 284 NOT NULL WITH DEFAULT ''
,TVARCHAR   VARCHAR (70)
,TINT       INT           NOT NULL DEFAULT 2
,TTIMESTAMP   TIMESTAMP    NOT NULL DEFAULT CURRENT TIMESTAMP
,TTIME        TIME  NOT NULL WITH DEFAULT
,TDATE        DATE      NOT NULL WITH DEFAULT
) RcdFmt SEG38R;

Label On Table &LIB/SEGFFAUT38 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT38
(TDEC          Text Is 'DECIMAL'
,TCHAR         Text Is 'CHAR'
,TCHAR2        Text Is 'CHAR'
,TVARCHAR      Text Is 'VARCHAR'
,TINT          Text Is 'INT'
,TTIMESTAMP       TEXT IS 'TTIMESTAMP'
,TTIME            TEXT IS 'TIME'
,TDATE            TEXT IS 'TDATE     '
 );

Label On Column &LIB/SEGFFAUT38
(TDEC               Is 'T_DECIMAL'
,TCHAR              Is 'T_CHAR'
,TCHAR2             Is 'T_TCHAR2'
,TVARCHAR           Is 'T_VARCHAR'
,TINT               Is 'T_INT'
,TTIMESTAMP            IS 'T_TIMESTAMP'
,TTIME                 IS 'T_TIME    '
,TDATE                 IS 'T_DATE    '
 );
