Create Table &LIB/SEGFFAUT09
(TDECFLOAT        DECFLOAT      NOT NULL WITH DEFAULT
) RcdFmt SEG09R;

Label On Table &LIB/SEGFFAUT09 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT09
(TDECFLOAT         TEXT IS 'TDECFLOAT     '
 );

Label On Column &LIB/SEGFFAUT09
(TDECFLOAT              Is 'T_DECFLOAT    '
 );
