Create Table &LIB/SEGFFAUT37
(TBLOBK        BLOB  (200K)
,TBLOBM        BLOB  (20M)
,TBLOBG        BLOB  (1G)
,TNUMERIC1       NUMERIC (20)  NOT NULL WITH DEFAULT
,TNUMERIC2       NUMERIC (12)  NOT NULL WITH DEFAULT
,TNUMERIC3       NUMERIC (20)  NOT NULL WITH DEFAULT
,TNUMERIC4       NUMERIC (12)  NOT NULL WITH DEFAULT
,TNUMERIC5       NUMERIC (20)  NOT NULL WITH DEFAULT
,TNUMERIC6       NUMERIC (15,4)   NOT NULL WITH DEFAULT
,TNUMERIC7       NUMERIC (20,4)   NOT NULL WITH DEFAULT
,TNUMERIC8       NUMERIC (15,4)   NOT NULL WITH DEFAULT
,TNUMERIC9       NUMERIC (20,4)   NOT NULL WITH DEFAULT
,TNUMERIC10      NUMERIC (15,4)   NOT NULL WITH DEFAULT
,TDEC1    DEC  (10, 2)   NOT NULL DEFAULT 0
,TDEC2    DEC  (10, 2)   NOT NULL DEFAULT 0
,TDEC3    DEC  (10, 2)   NOT NULL DEFAULT 0
,TDEC4    DEC  (10, 2)   NOT NULL DEFAULT 0
,TDEC5    DEC  (10, 2)   NOT NULL DEFAULT 0
) RcdFmt SEG37R;

Label On Table &LIB/SEGFFAUT37 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT37
(TBLOBK   TEXT IS 'TBLOBK'
,TBLOBM   TEXT IS 'TBLOBM'
,TBLOBG   TEXT IS 'TBLOBG'
,TNUMERIC1        TEXT IS 'TNUMERIC1    '
,TNUMERIC2        TEXT IS 'TNUMERIC2    '
,TNUMERIC3        TEXT IS 'TNUMERIC3    '
,TNUMERIC4        TEXT IS 'TNUMERIC4    '
,TNUMERIC5        TEXT IS 'TNUMERIC5    '
,TNUMERIC6        TEXT IS 'TNUMERIC6    '
,TNUMERIC7        TEXT IS 'TNUMERIC7    '
,TNUMERIC8        TEXT IS 'TNUMERIC8    '
,TNUMERIC9        TEXT IS 'TNUMERIC9    '
,TNUMERIC10       TEXT IS 'TNUMERIC10   '
,TDEC1            TEXT IS 'DECIMAL     '
,TDEC2            TEXT IS 'DECIMAL     '
,TDEC3            TEXT IS 'DECIMAL     '
,TDEC4            TEXT IS 'DECIMAL     '
,TDEC5            TEXT IS 'DECIMAL     '
 );

Label On Column &LIB/SEGFFAUT37
(TBLOBK        Is 'T_BLOBK'
,TBLOBM        IS 'T_BLOBM'
,TBLOBG        IS 'T_BLOBG'
,TNUMERIC1             IS 'T_NUMERIC1   '
,TNUMERIC2             IS 'T_NUMERIC2   '
,TNUMERIC3             IS 'T_NUMERIC3   '
,TNUMERIC4             IS 'T_NUMERIC4   '
,TNUMERIC5             IS 'T_NUMERIC5   '
,TNUMERIC6             IS 'T_NUMERIC6   '
,TNUMERIC7             IS 'T_NUMERIC7   '
,TNUMERIC8             IS 'T_NUMERIC8   '
,TNUMERIC9             IS 'T_NUMERIC9   '
,TNUMERIC10            IS 'T_NUMERIC10  '
,TDEC1                 IS 'T_DECIMAL1'
,TDEC2                 IS 'T_DECIMAL2'
,TDEC3                 IS 'T_DECIMAL3'
,TDEC4                 IS 'T_DECIMAL4'
,TDEC5                 IS 'T_DECIMAL5'
 );
