Create Table &LIB/SEGFFAUT25
(TDATALINK         DATALINK   (300)  LINKTYPE URL NO LINK CONTROL NOT NULL WITH
 DEFAULT
) RcdFmt SEG25R;

Label On Table &LIB/SEGFFAUT25 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT25
(TDATALINK        TEXT IS 'TDATALINK'
 );

Label On Column &LIB/SEGFFAUT25
(TDATALINK         Is 'T_DATALINK'
 );
