Create Table &LIB/SEGFFAUT20
(TBLOBK        BLOB  (200K)
,TBLOBM        BLOB  (20M)
,TBLOBG        BLOB  (1G)
) RcdFmt SEG20R;

Label On Table &LIB/SEGFFAUT20 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT20
(TBLOBK   TEXT IS 'TBLOBK'
,TBLOBM   TEXT IS 'TBLOBM'
,TBLOBG   TEXT IS 'TBLOBG'
 );

Label On Column &LIB/SEGFFAUT20
(TBLOBK        Is 'T_BLOBK'
,TBLOBM        IS 'T_BLOBM'
,TBLOBG        IS 'T_BLOBG'
 );
