Create Table &LIB/SEGFFAUT11
(TDECIMAL        DECIMAL    (60) NOT NULL WITH DEFAULT
,TDECIMALD       DECIMAL (20, 4) NOT NULL WITH DEFAULT
,TNUMERIC        NUMERIC (20)  NOT NULL WITH DEFAULT
) RcdFmt SEG11R;

Label On Table &LIB/SEGFFAUT11 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT11
(TDECIMAL         TEXT IS 'TDECIMAL     '
,TDECIMALD        TEXT IS 'TDECIMAL DEC '
,TNUMERIC         TEXT IS 'TNUMERIC     '
 );

Label On Column &LIB/SEGFFAUT11
(TDECIMAL              Is 'T_DECIMAL    '
,TDECIMALD             Is 'T_DECIMAL DEC'
,TNUMERIC              IS 'T_NUMERIC    '
 );
