Create Table &LIB/SEGFFAUT05
(TSMALLINT        SMALLINT      NOT NULL WITH DEFAULT
,TINTEGER        INTEGER      NOT NULL WITH DEFAULT
,TNUMERIC1       NUMERIC (20)  NOT NULL WITH DEFAULT
,TNUMERIC2       NUMERIC (15,4)   NOT NULL WITH DEFAULT
,TNUMERIC3       NUMERIC (20)  NOT NULL WITH DEFAULT
,TNUMERIC4       NUMERIC (15,4)   NOT NULL WITH DEFAULT
,TNUMERIC5       NUMERIC (20)  NOT NULL WITH DEFAULT
,TNUMERIC6       NUMERIC (15,4)   NOT NULL WITH DEFAULT
) RcdFmt SEG05R;

Label On Table &LIB/SEGFFAUT05 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT05
(TSMALLINT         TEXT IS 'TSMALLINT     '
,TINTEGER         TEXT IS 'TINTEGER     '
,TNUMERIC1        TEXT IS 'TNUMERIC1    '
,TNUMERIC2        TEXT IS 'TNUMERIC2    '
,TNUMERIC3        TEXT IS 'TNUMERIC3    '
,TNUMERIC4        TEXT IS 'TNUMERIC4    '
,TNUMERIC5        TEXT IS 'TNUMERIC5    '
,TNUMERIC6        TEXT IS 'TNUMERIC6    '
 );

Label On Column &LIB/SEGFFAUT05
(TSMALLINT              Is 'T_SMALLINT    '
,TINTEGER              IS 'T_INTEGER    '
,TNUMERIC1             IS 'T_NUMERIC1   '
,TNUMERIC2             IS 'T_NUMERIC2   '
,TNUMERIC3             IS 'T_NUMERIC3   '
,TNUMERIC4             IS 'T_NUMERIC4   '
,TNUMERIC5             IS 'T_NUMERIC5   '
,TNUMERIC6             IS 'T_NUMERIC6   '
 );
