Create Table &LIB/SEGFFAUT02
(TTIMESTAMP   TIMESTAMP    NOT NULL DEFAULT CURRENT TIMESTAMP
 ,TTIME        TIME  NOT NULL WITH DEFAULT
 ,TDATE        DATE      NOT NULL WITH DEFAULT
 ,TSMALLINT       SMALLINT     NOT NULL WITH DEFAULT
 ,TBIGINT         BIGINT       NOT NULL WITH DEFAULT
 ,TNUMERIC        NUMERIC (20)  NOT NULL WITH DEFAULT
 ,TNUMERICD       NUMERIC (15,4)   NOT NULL WITH DEFAULT
 ,TDOUBLE         DOUBLE          NOT NULL DEFAULT
 ,TCLOB           CLOB   (100)    NOT NULL DEFAULT
 ,TDBCLOB         DBCLOB   (60)     NOT NULL DEFAULT
) RcdFmt SEG02R;

Label On Table &LIB/SEGFFAUT02 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT02
(TTIMESTAMP    TEXT IS 'TTIMESTAMP'
,TTIME            TEXT IS 'TIME'
,TDATE            TEXT IS 'TDATE     '
,TSMALLINT        TEXT IS 'TSMALLINT     '
,TNUMERIC         TEXT IS 'TNUMERIC     '
,TNUMERICD        TEXT IS 'TNUMERIC DEC '
,TDOUBLE          TEXT IS 'TDOUBLE'
,TCLOB            TEXT IS 'TCLOB'
,TDBCLOB          TEXT IS 'TDBCLOB'
 );

Label On Column &LIB/SEGFFAUT02
(TTIMESTAMP         Is 'T_TIMESTAMP'
,TTIME                 IS 'T_TIME    '
,TDATE                 IS 'T_DATE    '
,TSMALLINT             IS 'T_SMALLINT    '
,TNUMERIC              IS 'T_NUMERIC    '
,TNUMERICD             IS 'T_NUMERIC DEC'
,TDOUBLE               IS 'T_DOUBLE'
,TCLOB                 IS 'T_CLOB'
,TDBCLOB               IS 'T_DBCLOB'
 );
