Create Table &LIB/SEGFFAUT14
(TREAL    REAL            NOT NULL DEFAULT
,TSMALLINT       SMALLINT     NOT NULL WITH DEFAULT
,TBIGINT         BIGINT       NOT NULL WITH DEFAULT
,TNUMERIC        NUMERIC (30)  NOT NULL WITH DEFAULT
,TNUMERICD       NUMERIC (15,4)   NOT NULL WITH DEFAULT
,TDOUBLE         DOUBLE          NOT NULL DEFAULT
,TCLOB           CLOB   (100)    NOT NULL DEFAULT
) RcdFmt SEG14R;

Label On Table &LIB/SEGFFAUT14 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT14
(TREAL    TEXT IS 'TREAL'
,TSMALLINT        TEXT IS 'TSMALLINT     '
,TNUMERIC         TEXT IS 'TNUMERIC     '
,TNUMERICD        TEXT IS 'TNUMERIC DEC '
,TDOUBLE          TEXT IS 'TDOUBLE'
,TCLOB            TEXT IS 'TCLOB'
 );

Label On Column &LIB/SEGFFAUT14
(TREAL         Is 'T_REAL'
,TSMALLINT             IS 'T_SMALLINT    '
,TNUMERIC              IS 'T_NUMERIC    '
,TNUMERICD             IS 'T_NUMERIC DEC'
,TDOUBLE               IS 'T_DOUBLE'
,TCLOB                 IS 'T_CLOB'
 );
