--Tabla Seguridades Resumen por Objeto
--Cristhian Herrera Bancolombia Enero 2020
Create Table &LIB.SEGFFUSRPE(
CODIGO INTEGER IMPLICITLY HIDDEN GENERATED ALWAYS AS IDENTITY
(START WITH 1 INCREMENT BY 1),
BIBLIOTECA CHAR(10) NOT NULL CHECK (BIBLIOTECA <> ''),
OBJETO  CHAR(10) NOT NULL CHECK (OBJETO <> ''),
TIPOOBJ  CHAR(10) NOT NULL CHECK (TIPOOBJ <> ''),
TS_CREATE TIMESTAMP NOT NULL IMPLICITLY HIDDEN
WITH DEFAULT current_timestamp,
TS_UPDATE TIMESTAMP NOT NULL IMPLICITLY HIDDEN
FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP,
CONSTRAINT &LIB.PK_SEGFFUSRPE PRIMARY KEY(BIBLIOTECA,OBJETO,TIPOOBJ));

Label On Table &LIB.SEGFFUSRPE Is 'Tabla SEG Resumen por Objeto';


