--AW1192003_BC_1:"RUNSQLSTM SRCFILE(R1EDM/EDMSRC) SRCMBR(EDMFFSPIFS) "
--AW1192003_BC_2:"COMMIT(*NONE)"
--AW1192003_OBJTYPE:"*FILE"
CREATE OR REPLACE TABLE &LIB/SEGFFAUTOR (
LIBOBJ       CHAR       (10)   ,
OBJETO       CHAR       (10)   ,
TIPOBJ       CHAR       (7)    ,
USRAUT       CHAR       (10)   ,
TIPAUT       CHAR       (10)   ,
ESTADO       CHAR       (1)    ,
FECHAUT      CHAR       (8)    ,
HORAAUT      CHAR       (6)    ,
USUCREA      CHAR       (10)   ,
FECCREA      TIMESTAMP         ,
USUMODIF     CHAR       (10)   ,
FECMODIF     TIMESTAMP         ,
CONSTRAINT PK_AUTOR PRIMARY KEY (OBJETO, LIBOBJ,TIPOBJ,USRAUT))
RCDFMT   REGAUTOR;

LABEL ON TABLE &LIB/SEGFFAUTOR  Is
'REGISTRA AUTORIZACIONES';

LABEL ON &LIB/SEGFFAUTOR (
OBJETO        Text Is  'OBJETO',
LIBOBJ        Text Is  'LIBRERIA',
TIPOBJ        TEXT IS  'TIPO OBJETO',
TIPAUT        Text Is  'TIPO AUTORIZACIÓN',
USRAUT        Text Is  'USUARIO AUTORIZADO',
FECHAUT       TEXT IS  'FECHA AUTORIZACIÓN',
HORAAUT       TEXT IS  'HORA AUTORIZACIÓN',
Estado        Text Is  'ESTADO',
UsuCrea       Text Is  'USUARIO CREA',
FecCrea       Text Is  'FECHA CREA',
UsuModif      Text Is  'USUARIO MODIFICA',
FecModif      Text Is  'FECHA MODIFICACIÓN');

LABEL ON COLUMN &LIB/SEGFFAUTOR (
OBJETO             IS  'OBJETO',
LIBOBJ             IS  'LIBRERIA',
TIPOBJ             IS  'TIPO OBJETO',
TIPAUT             IS  'TIPO AUTORIZACIÓN',
USRAUT             IS  'USUARIO AUTORIZADO',
FECHAUT            IS  'FECHA AUTORIZACIÓN',
HORAAUT            IS  'HORA AUTORIZACIÓN',
ESTADO             IS  'ESTADO',
USUCREA            IS  'USUARIO CREA',
FECCREA            IS  'FECHA CREA',
USUMODIF           IS  'USUARIO MODIFICA',
FECMODIF           IS  'FECHA MODIFICACIÓN');
