Create Table &LIB/SEGFFAUT12
(TBINARY    BINARY   (115)    NOT NULL DEFAULT
,TVARBINARY VARBINARY(115)    NOT NULL DEFAULT
) RcdFmt SEG12R;

Label On Table &LIB/SEGFFAUT12 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT12
(TBINARY    TEXT IS 'TBINARY'
,TVARBINARY TEXT IS 'TVARBINARY'
 );

Label On Column &LIB/SEGFFAUT12
(TBINARY         Is 'T_BINARY'
,TVARBINARY      Is 'T_VARBINARY'
 );
