Create Table &LIB/SEGFFAUT39
(TBINARY    BINARY   (115)    NOT NULL DEFAULT
,TVARBINARY VARBINARY(115)    NOT NULL DEFAULT
,TCLOB           CLOB   (100)    NOT NULL DEFAULT
,TDBCLOB         DBCLOB   (60)     NOT NULL DEFAULT
,TTIMESTAMP   TIMESTAMP    NOT NULL DEFAULT CURRENT TIMESTAMP
,TTIME        TIME  NOT NULL WITH DEFAULT
,TDATE        DATE      NOT NULL WITH DEFAULT
) RcdFmt SEG39R;

Label On Table &LIB/SEGFFAUT39 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT39
(TBINARY    TEXT IS 'TBINARY'
,TVARBINARY TEXT IS 'TVARBINARY'
,TCLOB            TEXT IS 'TCLOB'
,TDBCLOB          TEXT IS 'TDBCLOB'
,TTIMESTAMP       TEXT IS 'TTIMESTAMP'
,TTIME            TEXT IS 'TIME'
,TDATE            TEXT IS 'TDATE     '
 );

Label On Column &LIB/SEGFFAUT39
(TBINARY         Is 'T_BINARY'
,TVARBINARY      Is 'T_VARBINARY'
,TCLOB           IS 'T_CLOB'
,TDBCLOB         IS 'T_DBCLOB'
,TTIMESTAMP      IS 'T_TIMESTAMP'
,TTIME           IS 'T_TIME    '
,TDATE           IS 'T_DATE    '
 );
