Create Table &LIB/SEGFFAUT17
(TCLOB         CLOB   (40)     NOT NULL DEFAULT
,TDBCLOB     DBCLOB   (60)     NOT NULL DEFAULT

) RcdFmt SEG17R;

Label On Table &LIB/SEGFFAUT17 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT17
(TCLOB    TEXT IS 'TCLOB'
,TDBCLOB  TEXT IS 'TDBCLOB'
 );

Label On Column &LIB/SEGFFAUT17
(TCLOB         Is 'T_CLOB'
,TDBCLOB       IS 'T_DBCLOB'
 );
