Create Table &LIB/SEGFFAUT22
(TINTEGER        INTEGER      NOT NULL WITH DEFAULT
,TSMALLINT       SMALLINT     NOT NULL WITH DEFAULT
,TBIGINT         BIGINT       NOT NULL WITH DEFAULT
,TNUMERIC        NUMERIC (20)  NOT NULL WITH DEFAULT
,TNUMERICD       NUMERIC (15,4)  NOT NULL WITH DEFAULT
) RcdFmt SEG22R;

Label On Table &LIB/SEGFFAUT22 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT22
(TINTEGER         TEXT IS 'TINTEGER     '
,TSMALLINT        TEXT IS 'TSMALLINT     '
,TBIGINT          TEXT IS 'TBIGINT     '
,TNUMERIC         TEXT IS 'TNUMERIC     '
,TNUMERICD        TEXT IS 'TNUMERIC DEC '
 );

Label On Column &LIB/SEGFFAUT22
(TINTEGER              Is 'T_INTEGER    '
,TSMALLINT             IS 'T_SMALLINT    '
,TINTEGER              IS 'T_INTEGER    '
,TNUMERIC              IS 'T_NUMERIC    '
,TNUMERICD             IS 'T_NUMERIC DEC'
 );
