--AW1192003_BC_1:"RUNSQLSTM SRCFILE(R1SEG/SEGSRC) SRCMBR(SEGFFMNSQL) "
--AW1192003_BC_2:"COMMIT(*NONE)"
--AW1192003_OBJTYPE:"*FILE"

CREATE OR REPLACE TABLE &LIB/SEGFFMNSQL (
NOMID        CHAR       (55)    ,
QRYCONSUL    VARCHAR    (1000),
ESTADO       CHAR       (1),
USUARIO      CHAR       (10),
FECHACREA    NUMERIC    (8),
HORACREA     NUMERIC    (6),
FECHAUPD     NUMERIC    (8),
CONSTRAINT PK_MNSQL PRIMARY KEY (NOMID))
RCDFMT   REGMNSQL;

LABEL ON TABLE &LIB/SEGFFMNSQL  Is
'SCIPTS PARA INFORME';
