Create Table &LIB/SEGFFAUT31
(TGRAPHIC    GRAPHIC   (100)    NOT NULL DEFAULT
,TVARGRAPHIC VARGRAPHIC(90)    NOT NULL DEFAULT
,TINTEGER        INTEGER      NOT NULL WITH DEFAULT
,TSMALLINT       SMALLINT     NOT NULL WITH DEFAULT
,TBIGINT         BIGINT       NOT NULL WITH DEFAULT
,TCHAR           CHAR (1000)   NOT NULL DEFAULT ''
,TCHAR2          CHAR (300) CCSID 284 NOT NULL WITH DEFAULT ''
,TINT            INT           NOT NULL DEFAULT 0
) RcdFmt SEG31R;

Label On Table &LIB/SEGFFAUT31 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT31
(TGRAPHIC          TEXT IS'TGRAPHIC'
,TVARGRAPHIC       TEXT IS 'TVARGRAPHIC'
,TSMALLINT         TEXT IS 'TSMALLINT     '
,TBIGINT           TEXT IS 'TBIGINT     '
,TCHAR             TEXT IS 'CHAR'
,TCHAR2            TEXT IS 'CHAR'
,TINT              TEXT IS 'INT'
 );

Label On Column &LIB/SEGFFAUT31
(TGRAPHIC         Is 'T_GRAPHIC'
,TVARGRAPHIC      Is 'T_VARGRAPHIC'
,TSMALLINT        IS 'T_SMALLINT    '
,TBIGINT          IS 'T_BIGINT    '
,TCHAR            IS 'T_CHAR'
,TCHAR2           IS 'T_TCHAR2'
,TINT             IS 'T_INT'
 );
