Create Table &LIB/SEGFFAUT29
(TBLOBK        BLOB  (200K)
,TBLOBM        BLOB  (20M)
,TBLOBG        BLOB  (1G)
,TNUMERIC        NUMERIC (20)  NOT NULL WITH DEFAULT
,TNUMERICD       NUMERIC (15,4)   NOT NULL WITH DEFAULT
,TDOUBLE       DOUBLE          NOT NULL DEFAULT
,TCLOB         CLOB   (100)    NOT NULL DEFAULT
,TDBCLOB        DBCLOB   (60)     NOT NULL DEFAULT
) RcdFmt SEG29R;

Label On Table &LIB/SEGFFAUT29 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT29
(TBLOBK   TEXT IS 'TBLOBK'
,TBLOBM   TEXT IS 'TBLOBM'
,TBLOBG   TEXT IS 'TBLOBG'
,TNUMERIC         TEXT IS 'TNUMERIC     '
,TNUMERICD        TEXT IS 'TNUMERIC DEC '
,TDOUBLE          TEXT IS 'TDOUBLE'
,TCLOB            TEXT IS 'TCLOB'
,TDBCLOB          TEXT IS 'TDBCLOB'
 );

Label On Column &LIB/SEGFFAUT29
(TBLOBK        Is 'T_BLOBK'
,TBLOBM        IS 'T_BLOBM'
,TBLOBG        IS 'T_BLOBG'
,TNUMERIC              IS 'T_NUMERIC    '
,TNUMERICD             IS 'T_NUMERIC DEC'
,TDOUBLE               IS 'T_DOUBLE'
,TCLOB                 IS 'T_CLOB'
,TDBCLOB               IS 'T_DBCLOB'
 );
