Create Table &LIB/SEGFFAUT40
(TCHAR           CHAR (50)     NOT NULL DEFAULT ''
,TNUMERIC        NUMERIC (20)  NOT NULL WITH DEFAULT
,TNUMERICD       NUMERIC (15,4)   NOT NULL WITH DEFAULT

,TXML         XML        NOT NULL WITH DEFAULT
) RcdFmt SEG40R;

Label On Table &LIB/SEGFFAUT40 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT40
(TCHAR            TEXT IS 'CHAR'
,TNUMERIC         TEXT IS 'TNUMERIC     '
,TNUMERICD        TEXT IS 'TNUMERIC DEC '
,TXML    TEXT IS 'TXML'
 );

Label On Column &LIB/SEGFFAUT40
(TCHAR                 IS 'T_CHAR'
,TNUMERIC              IS 'T_NUMERIC    '
,TNUMERICD             IS 'T_NUMERIC DEC'
,TXML         IS 'T_XML'
 );
