--AW1192003_BC_1:"RUNSQLSTM SRCFILE(R1SEG/SEGSRC) SRCMBR(SEGFFEXCFE) "
--AW1192003_BC_2:"COMMIT(*NONE)"
--AW1192003_OBJTYPE:"*FILE"

CREATE OR REPLACE TABLE &LIB/SEGFFEXCFE (
NROID        CHAR       (15)    ,
FECHAFIN     NUMERIC    (8)    ,
CONSTRAINT PK_FECFN PRIMARY KEY (NROID))
RCDFMT   REGFECFN;

LABEL ON TABLE &LIB/SEGFFEXCFE  Is
'FECHA FIN EXCEPCIONES';
