Create Table &LIB/SEGFFAUT13
(TGRAPHIC    GRAPHIC   (115)    NOT NULL DEFAULT
,TVARGRAPHIC VARGRAPHIC(115)    NOT NULL DEFAULT
) RcdFmt SEG13R;

Label On Table &LIB/SEGFFAUT13 Is 'TIPOS DE DATOS PARA PRUEBAS LZ ';
Label On  &LIB/SEGFFAUT13
(TGRAPHIC    TEXT IS 'TGRAPHIC'
,TVARGRAPHIC TEXT IS 'TVARGRAPHIC'
 );

Label On Column &LIB/SEGFFAUT13
(TGRAPHIC         Is 'T_GRAPHIC'
,TVARGRAPHIC      Is 'T_VARGRAPHIC'
 );
