----------------------------------------------------------------------
-- NOMBRE DE SCRIPT....: CREAR TABLA BASE.                          --
-- DESCRIPCIÓN.........: TABLA - LOG HISTORICO DEPURACIONES         --
-- TIPO OBJETO.........: TABLE                                      --
-- REQUERIMIENTO.......: EVC00032-TRANSVERSALES ISERIES.            --
-- SUBDOMINIO..........: TRANSVERSALES DE APOYO ISERIES.            --
-- FECHA DE CREACIÓN...: MAYO  2023                                 --
-- AUTOR...............: STEVEN PEREZ GOMEZ PERSONALSOFT            --
-- BASE DE DATOS RELACIONAL:  DB2 FOR I                             --
----------------------------------------------------------------------
-- MODIFICACIONES        :                                           --
-- FECHA DE MODIFICACIÓN :                                          --
-- AUTOR...............  :                                          --
-- DESCRIPCIÓN ......... :                                          --
-- REQUERIMIENTO.........:                                          --
----------------------------------------------------------------------

-- SE DEFINE LIBRERIA DE TRABAJO
  SET CURRENT SCHEMA &LIB; -- CREACION DE TABLA - LOG HISTORICO DEPURACIONES

-- CREAR TABLA LOG HISTORICO DEPURACIONES
  CREATE OR REPLACE TABLE &LIB/LOG_HISTORICO_DEPURACIONES
  FOR SYSTEM NAME SEGTBHIDEP(

--DEFINICION DE CAMPOS
  PROCESO_DEPURADOR       FOR COLUMN IDPROCESO  CHAR(10)
                          NOT NULL DEFAULT '' ,

  FECHA_INICIO_PLAN       FOR COLUMN FECINIPLA  DATE
                          NOT NULL DEFAULT CURRENT DATE ,

  HORA_INICIO_PLAN        FOR COLUMN HORINIPLAN TIME
                          NOT NULL DEFAULT CURRENT TIME ,

  FRECUENCIA_PROCESO      FOR COLUMN FRECUENCIA CHAR(1)
                          NOT NULL DEFAULT '' ,

  HORA_INICIO_EJECUCION   FOR COLUMN HORAINIEJE TIMESTAMP
                          NOT NULL DEFAULT CURRENT TIMESTAMP ,

  HORA_FIN_EJECUCION      FOR COLUMN HORAFINEJE TIMESTAMP
                          NOT NULL DEFAULT CURRENT TIMESTAMP ,

  TIEMPO_EJECUCION        FOR COLUMN TIMEEJECUC NUMERIC (06,0)
                          NOT NULL DEFAULT 0 ,

  HORA_ULT_VALIDACION     FOR COLUMN HORAULTVAL TIMESTAMP
                          NOT NULL DEFAULT CURRENT TIMESTAMP ,

  ESTADO_PROCESO          FOR COLUMN ESTPROCESO CHAR(10)
                          NOT NULL DEFAULT '' ,

  TIPO_DEPURACION         FOR COLUMN TIPDEPUR CHAR(10)
                          NOT NULL DEFAULT '' ,

  DATOS_JOB               FOR COLUMN DATOSJOB CHAR(28)
                          NOT NULL DEFAULT '' ,

  OBSERBACION_PROCESO     FOR COLUMN OBSERPRO VARCHAR(100)
                          NOT NULL DEFAULT '',

  FECHA_REGISTRO         FOR COLUMN FECREGIS TIMESTAMP
                         NOT NULL DEFAULT CURRENT TIMESTAMP,

 -- CLAVE PRIMARIA
  CONSTRAINT SEGTBHIDEP_PK PRIMARY KEY(PROCESO_DEPURADOR, FECHA_REGISTRO)
   )

  -- FORMATO DEL REGISTRO
 RCDFMT REGHIDEP;

 -- ETIQUETA DE LA TABLA
   LABEL ON TABLE &LIB/SEGTBHIDEP IS
   'TABLA LOG HITORICO DEPURACIONES';

   COMMENT ON TABLE &LIB/SEGTBHIDEP IS
  'TABLA LOG HITORICO DEPURACIONES';

-- ATRIBUTO DE TEXTO DE LOS CAMPOS
   LABEL ON COLUMN  &LIB/SEGTBHIDEP
   (
    PROCESO_DEPURADOR      IS     'PROCESO             DEPURADOR' ,
    FECHA_INICIO_PLAN      IS     'FECHA INICIO        PLANIFICDA' ,
    HORA_INICIO_PLAN       IS     'HORA INICIO         PLANIFICADA' ,
    FRECUENCIA_PROCESO     IS     'FRECUENCIA DEL      PROCESO' ,
    HORA_INICIO_EJECUCION  IS     'HORA INICIO DE      EJECUCION' ,
    HORA_FIN_EJECUCION     IS     'HORA FIN DE         EJECUCION' ,
    TIEMPO_EJECUCION       IS     'TIEMPO DE           EJECUCION',
    HORA_ULT_VALIDACION    IS     'HORA ULTIMA         VALIDACION',
    ESTADO_PROCESO         IS     'ESTADO DEL          PROCESO',
    TIPO_DEPURACION        IS     'TIPO DE             DEPURACION',
    DATOS_JOB              IS     'DATOS DEL           JOB',
    OBSERBACION_PROCESO    IS     'OBSERVACIONES DEL   PROCESO',
    FECHA_REGISTRO         IS     'FECHA DEL           REGISTRO'
    );

-- ATRIBUTO DE TEXTO DE LOS CAMPOS
   LABEL ON COLUMN &LIB/SEGTBHIDEP
   (
    PROCESO_DEPURADOR      TEXT IS  'CODIGO DEL PROCESO DEPURADOR' ,
    FECHA_INICIO_PLAN      TEXT IS  'FECHA INICIO PLANIFICDA' ,
    HORA_INICIO_PLAN       TEXT IS  'HORA INICIO PLANIFICADA' ,
    FRECUENCIA_PROCESO     TEXT IS  'FRECUENCIA DEL PROCESO' ,
    HORA_INICIO_EJECUCION  TEXT IS  'HORA INICIO DE EJECUCION' ,
    HORA_FIN_EJECUCION     TEXT IS  'HORA FIN DE EJECUCION' ,
    TIEMPO_EJECUCION       TEXT IS  'TIEMPO DE EJECUCION',
    HORA_ULT_VALIDACION    TEXT IS  'HORA ULTIMA VALIDACION',
    ESTADO_PROCESO         TEXT IS  'ESTADO: ACTIVO, HOLD, SCD, ETC..',
    TIPO_DEPURACION        TEXT IS  'DEPURACION: ARCHIVO/IFS',
    DATOS_JOB              TEXT IS  'DATOS: NUMERO/USURIO/TRABAJO',
    OBSERBACION_PROCESO    TEXT IS  'OBSERVACIONES',
    FECHA_REGISTRO         TEXT IS  'FECHA REGISTRO'
    );
