 --AW1192003_BC_1:"RUNSQLSTM SRCFILE(R1SEG/SEGSRC) SRCMBR(SEGVWDBLAU) "
 --AW1192003_BC_2:"COMMIT(*NONE)"
 --AW1192003_OBJTYPE:"*FILE"
--------------------------------------------------------------------------------
-- TABLA    : &LIB/SEGVWDBLAU
-- OBJETIVO : VISTA PARA JOURNAL DE AUTORIZACIONES MASIVAS.
-- FECHA    : OCTUBRE DE 2024
-- AUTOR    : FABIAN ANDDRES GIRALDO FRANCO
--------------------------------------------------------------------------------

 CREATE OR REPLACE VIEW &LIB.SEGVWDBLAU AS SELECT SEQUENCE_NUMBER,
 SUBSTR(CAST(PATH_NAME AS VARCHAR(100)),26) AS PN FROM
 TABLE(QSYS2.DISPLAY_JOURNAL('&LIB', 'SEGJRNAUT')) AS JT
 WHERE JOURNAL_ENTRY_TYPE = 'JT'

