# Generated by Django 6.0.4 on 2026-06-01 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_model', models.CharField(choices=[('S', 'Simple'), ('A', 'Avanzado'), ('E', 'Experto')], default='S', max_length=1, verbose_name='Modelo de tabla')),
                ('table_name_long', models.CharField(max_length=128, verbose_name='Nombre largo de la tabla')),
                ('table_name_short', models.CharField(help_text='Nombre de archivo / miembro según convención IBM i (hasta 10).', max_length=10, verbose_name='Nombre corto de la tabla')),
                ('schema', models.CharField(help_text='Librería / esquema IBM i (obligatorio; máx. 10 caracteres).', max_length=10, verbose_name='Esquema / librería')),
                ('table_type', models.CharField(choices=[('PHYSICAL', 'Física'), ('LOGICAL', 'Lógica')], default='PHYSICAL', max_length=20, verbose_name='Tipo de tabla')),
                ('is_field_key', models.BooleanField(default=False, verbose_name='Tiene llave')),
                ('is_auto_key', models.BooleanField(default=False, verbose_name='Llave autogenerada')),
                ('status', models.CharField(choices=[('P', 'Proceso'), ('A', 'Activo'), ('I', 'Inactivo')], default='P', max_length=1, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('script_date', models.DateField(blank=True, null=True, verbose_name='Fecha de script')),
                ('script_generated', models.BooleanField(default=False, verbose_name='Script generado')),
                ('sp_associated', models.BooleanField(default=False, verbose_name='Procedimiento almacenado asociado')),
                ('mt_associated', models.BooleanField(default=False, verbose_name='Mantenimiento asociado')),
                ('pk_constraint_name', models.CharField(blank=True, help_text='Patrón A-Z0-9_. Opcional: null/vacío no emite CONSTRAINT nominado en DDL. Unicidad global si tiene valor.', max_length=30, null=True, verbose_name='Nombre del constraint de PK')),
                ('record_format_name', models.CharField(blank=True, help_text='Opcional. Si tiene valor, el script puede emitir RCDFMT.', max_length=30, null=True, verbose_name='Nombre record format (RCDFMT)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_design_headers', to='company.company', verbose_name='Compañía')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_design_headers_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_design_headers_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Diseño de tabla (cabecera)',
                'verbose_name_plural': 'Diseños de tabla (cabeceras)',
                'ordering': ['company', 'table_name_short'],
            },
        ),
        migrations.CreateModel(
            name='DetailTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reg', models.PositiveIntegerField(verbose_name='Orden de registro')),
                ('field_name_long', models.CharField(max_length=30, verbose_name='Nombre largo del campo')),
                ('field_name_short', models.CharField(max_length=10, verbose_name='Nombre corto del campo')),
                ('field_type', models.CharField(choices=[('CHAR', 'CHAR'), ('VARCHAR', 'VARCHAR'), ('CLOB', 'CLOB'), ('GRAPHIC', 'GRAPHIC'), ('VARGRAPHIC', 'VARGRAPHIC'), ('SMALLINT', 'SMALLINT'), ('INTEGER', 'INTEGER'), ('BIGINT', 'BIGINT'), ('DECIMAL', 'DECIMAL'), ('NUMERIC', 'NUMERIC'), ('DECFLOAT', 'DECFLOAT'), ('REAL', 'REAL'), ('DOUBLE', 'DOUBLE'), ('DATE', 'DATE'), ('TIME', 'TIME'), ('TIMESTAMP', 'TIMESTAMP'), ('BINARY', 'BINARY'), ('VARBINARY', 'VARBINARY'), ('BLOB', 'BLOB'), ('ROWID', 'ROWID'), ('XML', 'XML')], max_length=20, verbose_name='Tipo de dato')),
                ('field_length', models.PositiveIntegerField(default=0, help_text='Para tipos sin longitud fija usar 0; validar por tipo en services/ al generar DDL.', verbose_name='Longitud')),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Decimales')),
                ('allocate_length', models.PositiveIntegerField(blank=True, help_text='Suballocación DB2 for i: obligatorio al dar de alta VARCHAR o VARGRAPHIC (debe ser > 0 y ≤ longitud).', null=True, verbose_name='ALLOCATE (VARCHAR/VARGRAPHIC)')),
                ('column_label', models.CharField(blank=True, default='', help_text='Texto para LABEL ON COLUMN (máximo 20 caracteres).', max_length=20, verbose_name='Etiqueta (LABEL ON COLUMN … IS)')),
                ('column_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto (LABEL ON COLUMN … TEXT IS)')),
                ('is_key', models.BooleanField(default=False, verbose_name='Llave')),
                ('order_key', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Orden de llave')),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('P', 'Proceso')], default='A', max_length=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('script_generated', models.BooleanField(default=False, verbose_name='Script generado')),
                ('script_date', models.DateField(blank=True, null=True, verbose_name='Fecha de script')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_design_fields_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_design_fields_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='table_design.headertable', verbose_name='Cabecera de diseño')),
            ],
            options={
                'verbose_name': 'Campo de diseño de tabla',
                'verbose_name_plural': 'Campos de diseño de tabla',
                'ordering': ['header', 'order_reg'],
            },
        ),
        migrations.CreateModel(
            name='HeaderTableAdvanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Iteración hasta congelar columnas fijas en el modelo.', verbose_name='Parámetros (JSON)')),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_extension', to='table_design.headertable', verbose_name='Cabecera')),
            ],
            options={
                'verbose_name': 'Extensión avanzada de diseño de tabla',
                'verbose_name_plural': 'Extensiones avanzadas de diseño de tabla',
            },
        ),
        migrations.CreateModel(
            name='HeaderTableExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Iteración hasta congelar columnas fijas en el modelo.', verbose_name='Parámetros (JSON)')),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_extension', to='table_design.headertable', verbose_name='Cabecera')),
            ],
            options={
                'verbose_name': 'Extensión experta de diseño de tabla',
                'verbose_name_plural': 'Extensiones expertas de diseño de tabla',
            },
        ),
        migrations.CreateModel(
            name='DetailTableDb2Attributes',
            fields=[
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='db2_attributes', serialize=False, to='table_design.detailtable', verbose_name='Campo de diseño')),
                ('is_identity', models.BooleanField(default=False, help_text='Marca la columna como GENERATED ALWAYS AS IDENTITY en el script.', verbose_name='Columna IDENTITY')),
                ('ccsid', models.PositiveIntegerField(blank=True, help_text='Opcional. Para tipos de texto en DB2 i (p. ej. 284).', null=True, verbose_name='CCSID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name="LLAVE_SCRIPT CHAR(32) DEFAULT 'N/A' IMPLICITLY HIDDEN")),
                ('default_sql_expression', models.CharField(blank=True, help_text='CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP', max_length=200, null=True, verbose_name='DEFAULT como expresión SQL')),
                ('nullable', models.BooleanField(default=True, verbose_name='Permite nulos')),
                ('default_value', models.CharField(blank=True, help_text='IS_ACTIVE SMALLINT NOT NULL WITH DEFAUL , NOT NULL,NULL, ', max_length=50, null=True, verbose_name='Valor por defecto')),
                ('signed', models.BooleanField(default=True, verbose_name='Con signo')),
                ('is_unique', models.BooleanField(default=False, help_text='CODIGO_SKU     VARCHAR(30) UNIQUE,  ', verbose_name='Único')),
                ('is_indexed', models.BooleanField(default=False, verbose_name='Indexado')),
                ('check_constraint_sql', models.TextField(blank=True, default='', help_text="STATUS CHAR(1) CHECK (STATUS IN ('A','I','P'))", verbose_name='CHECK (expresión SQL)')),
                ('generated_kind', models.CharField(choices=[('NONE', 'Sin columna generada'), ('EXPR', 'GENERATED ALWAYS AS (expresión)'), ('RCTS', 'ROW CHANGE TIMESTAMP'), ('RBEGIN', 'GENERATED ALWAYS AS ROW BEGIN'), ('REND', 'GENERATED ALWAYS AS ROW END')], default='NONE', max_length=8, verbose_name='Tipo de columna generada')),
                ('generated_expression', models.TextField(blank=True, default='', help_text='Obligatorio si generated_kind=EXPR.', verbose_name='Expresión GENERATED ALWAYS AS')),
                ('fieldproc_program', models.CharField(blank=True, default='', help_text='DOCUMENTO VARCHAR(20) FIELDPROC CODASLIB/ENCRIPTAR_DOC', max_length=128, verbose_name='FIELDPROC (programa calificado)')),
                ('for_bit_data', models.BooleanField(default=False, help_text='DOCUMENTO VARCHAR(20) FOR BIT DATA', verbose_name='FOR BIT DATA')),
                ('compress_mode', models.CharField(choices=[('NONE', 'Sin compresión'), ('SYSTEM_DEFAULT', 'COMPRESS SYSTEM DEFAULT')], default='NONE', help_text='DOCUMENTO VARCHAR(20) COMPRESS SYSTEM DEFAULT', max_length=16, verbose_name='Compresión de columna')),
                ('identity_generation', models.CharField(choices=[('ALWAYS', 'GENERATED ALWAYS AS IDENTITY'), ('BY_DEFAULT', 'GENERATED BY DEFAULT AS IDENTITY')], default='ALWAYS', help_text='Aplica solo si is_identity es verdadero.', max_length=10, verbose_name='Modo IDENTITY')),
                ('mask_function', models.CharField(blank=True, default='', help_text="EMAIL VARCHAR(254) MASKED WITH (FUNCTION 'EMAIL')", max_length=64, verbose_name='Función MASKED WITH')),
                ('is_row_change_timestamp', models.BooleanField(default=False, verbose_name='ROW CHANGE TIMESTAMP')),
                ('is_generated_rowid', models.BooleanField(default=False, verbose_name='ROWID generado')),
                ('associated_trigger_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Trigger asociado (nombre)')),
                ('security_label', models.CharField(blank=True, default='', max_length=128, verbose_name='SECURITY LABEL')),
                ('temporal_role', models.CharField(choices=[('NONE', 'Ninguno'), ('ST_START', 'PERIOD SYSTEM_TIME (inicio)'), ('ST_END', 'PERIOD SYSTEM_TIME (fin)'), ('AT_START', 'PERIOD APPLICATION_TIME (inicio)'), ('AT_END', 'PERIOD APPLICATION_TIME (fin)')], default='NONE', max_length=12, verbose_name='Rol temporal (PERIOD / ROW BEGIN-END)')),
                ('user_defined_field', models.CharField(blank=True, default='', help_text='Ej.: Definido por el usuario', max_length=255, verbose_name='User Defined Field')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_design_field_db2_attrs_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_design_field_db2_attrs_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Atributos DB2 de columna',
                'verbose_name_plural': 'Atributos DB2 de columnas',
            },
        ),
        migrations.CreateModel(
            name='HeaderTableAutoKeyConfig',
            fields=[
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auto_key_config', serialize=False, to='table_design.headertable', verbose_name='Cabecera')),
                ('identity_start', models.PositiveIntegerField(blank=True, help_text='Parámetro global para GENERATED AS IDENTITY (p. ej. 1).', null=True, verbose_name='IDENTITY: START WITH')),
                ('identity_increment', models.PositiveIntegerField(blank=True, null=True, verbose_name='IDENTITY: INCREMENT BY')),
                ('identity_cache', models.PositiveIntegerField(blank=True, null=True, verbose_name='IDENTITY: CACHE')),
                ('identity_cycle', models.BooleanField(default=False, help_text='Si es verdadero, se emite CYCLE en el bloque IDENTITY cuando aplique.', verbose_name='IDENTITY: CYCLE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_design_auto_key_configs_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_design_auto_key_configs_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de llave autogenerada',
                'verbose_name_plural': 'Configuraciones de llave autogenerada',
            },
        ),
        migrations.AddIndex(
            model_name='headertable',
            index=models.Index(fields=['company', 'status'], name='table_desig_company_689679_idx'),
        ),
        migrations.AddIndex(
            model_name='headertable',
            index=models.Index(fields=['company', 'table_name_short'], name='table_desig_company_67bef1_idx'),
        ),
        migrations.AddConstraint(
            model_name='headertable',
            constraint=models.UniqueConstraint(fields=('company', 'table_name_short'), name='uq_table_design_header_company_table_short'),
        ),
        migrations.AddConstraint(
            model_name='headertable',
            constraint=models.UniqueConstraint(condition=models.Q(('pk_constraint_name__isnull', False)), fields=('pk_constraint_name',), name='uq_table_design_header_pk_constraint_name'),
        ),
        migrations.AddIndex(
            model_name='detailtable',
            index=models.Index(fields=['header', 'order_reg'], name='table_desig_header__efae75_idx'),
        ),
        migrations.AddIndex(
            model_name='detailtable',
            index=models.Index(fields=['header', 'field_name_short'], name='table_desig_header__897b3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='detailtable',
            constraint=models.UniqueConstraint(fields=('header', 'order_reg'), name='uq_table_design_field_header_order'),
        ),
        migrations.AddConstraint(
            model_name='detailtable',
            constraint=models.UniqueConstraint(fields=('header', 'field_name_short'), name='uq_table_design_field_header_short_name'),
        ),
    ]
