# Generated by Django 6.0.4 on 2026-06-01 21:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.SlugField(help_text='Identificador estable para integraciones y reportes.', unique=True, verbose_name='Código')),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual'), ('enterprise', 'Enterprise')], default='monthly', max_length=20, verbose_name='Periodo de facturación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en catálogo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('expired', 'Expirada'), ('canceled', 'Cancelada'), ('pending', 'Pendiente de pago')], default='active', max_length=20, verbose_name='Estado')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renovación automática')),
                ('integrity_signature', models.CharField(blank=True, default='', help_text='Recalculada en cada guardado; no editar manualmente en BD.', max_length=64, verbose_name='Huella de integridad (HMAC-SHA256)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='company.company', verbose_name='Compañía')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='Plan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='manual', max_length=50, verbose_name='Método de pago')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de transacción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol o cargo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='billing.subscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Contacto de suscripción',
                'verbose_name_plural': 'Contactos de suscripción',
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('subscription', 'email'), name='billing_subscriptioncontact_subscription_email_uniq_when_set')],
            },
        ),
    ]
