-- DEFINICION DE LA TABLA (CODAS table_design)
CREATE OR REPLACE TABLE LIBEVAL.EVAL_SQL_VARIANTS_TABLE
    FOR SYSTEM NAME EVLSQL001 (

    ID_REGISTRO FOR COLUMN IDREG001
        INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1
         NO MINVALUE NO MAXVALUE
         NO CYCLE NO ORDER CACHE 5
        ),

    CODIGO_ESTADO FOR COLUMN CODEST01
        CHAR(1) CCSID 284 NOT NULL DEFAULT 'A',

    VALOR_TOTAL FOR COLUMN VLRTOT01
        DECIMAL(15, 2) NULL DEFAULT 0,

    FECHA_CREACION FOR COLUMN FECCRE01
        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    DESCRIPCION_ITEM FOR COLUMN DESITEM1
        VARCHAR(120) ALLOCATE(80) NULL DEFAULT NULL,

    CONSTRAINT PK_EVLSQL001 PRIMARY KEY (IDREG001)
) RCDFMT EVLSQL0R;

LABEL ON TABLE LIBEVAL/EVLSQL001 IS 'EVAL_SQL_VARIANTS_TABLE';
COMMENT ON TABLE LIBEVAL/EVLSQL001 IS 'EVAL_SQL_VARIANTS_TABLE';

LABEL ON COLUMN LIBEVAL/EVLSQL001 (
    DESCRIPCION_ITEM                IS 'Descripcion'
);

LABEL ON COLUMN LIBEVAL/EVLSQL001 (
    DESCRIPCION_ITEM                TEXT IS 'Descripcion extendida del item'
);
