# Generated by Django 6.0.4 on 2026-06-01 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la plantilla')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('filename', models.CharField(blank=True, max_length=100, verbose_name='Nombre del archivo')),
                ('source_text', models.TextField(verbose_name='Contenido de la plantilla')),
                ('source_type', models.CharField(choices=[('DSPF', 'Pantalla (DDS)'), ('SQLRPGLE', 'Programa SQLRPGLE'), ('RPGLE', 'Programa RPGLE'), ('CLLE', 'Programa CLLE')], default='DSPF', max_length=20, verbose_name='Tipo de fuente')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('company', models.ForeignKey(blank=True, help_text='Nulo = plantilla global; con valor = plantilla de compañía.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_templates', to='company.company', verbose_name='Compañía')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_templates_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Plantilla fuente',
                'verbose_name_plural': 'Plantillas fuente',
                'ordering': ['company__name_short', 'name', '-version'],
                'indexes': [models.Index(fields=['company', 'source_type', 'status'], name='sources_sou_company_18fc6d_idx'), models.Index(fields=['name', 'version'], name='sources_sou_name_deba05_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'name', 'version'), name='uq_source_template_company_name_version'), models.UniqueConstraint(condition=models.Q(('filename__gt', '')), fields=('company', 'filename', 'version'), name='uq_source_template_company_filename_version_when_filename')],
            },
        ),
    ]
