# Generated by Django 6.0.4 on 2026-06-01 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('sources', '0001_initial'),
        ('sp_asistido', '0001_initial'),
        ('table_design', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name_short', models.CharField(max_length=10, verbose_name='Nombre corto')),
                ('name_long', models.CharField(max_length=50, verbose_name='Nombre largo')),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='Comentario')),
                ('status', models.CharField(choices=[('D', 'Borrador'), ('G', 'Generado'), ('E', 'Error'), ('I', 'Inactivo')], default='D', max_length=1, verbose_name='Estado')),
                ('current_step', models.PositiveSmallIntegerField(default=1, verbose_name='Paso actual')),
                ('is_generation_pending', models.BooleanField(default=False, verbose_name='Generación pendiente')),
                ('last_generation_at', models.DateTimeField(blank=True, null=True, verbose_name='Última generación')),
                ('last_generation_result', models.CharField(blank=True, choices=[('S', 'Success'), ('E', 'Error')], max_length=1, null=True, verbose_name='Resultado última generación')),
                ('last_error_message', models.CharField(blank=True, default='', max_length=300, verbose_name='Último error')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_definitions', to='company.company', verbose_name='Compañía')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('dspf_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_definitions_dspf', to='sources.sourcetemplate', verbose_name='Plantilla DSPF')),
                ('header_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_definitions', to='table_design.headertable', verbose_name='Tabla base')),
                ('sqlrpgle_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_definitions_sqlrpgle', to='sources.sourcetemplate', verbose_name='Plantilla SQLRPGLE')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Definición de mantenimiento',
                'verbose_name_plural': 'Definiciones de mantenimiento',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('event_type', models.CharField(choices=[('SAVE', 'Guardar'), ('GENERATE', 'Generar'), ('ERROR', 'Error')], max_length=20, verbose_name='Tipo de evento')),
                ('event_status', models.CharField(choices=[('S', 'Success'), ('E', 'Error')], max_length=1, verbose_name='Estado del evento')),
                ('event_message', models.CharField(max_length=300, verbose_name='Mensaje')),
                ('event_detail_json', models.JSONField(blank=True, null=True, verbose_name='Detalle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_logs', to='maintenance_builder.maintenancedefinition', verbose_name='Mantenimiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Bitácora de proceso',
                'verbose_name_plural': 'Bitácoras de proceso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceScriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('version', models.PositiveIntegerField(verbose_name='Versión')),
                ('script_sqlrpgle', models.TextField(verbose_name='Script SQLRPGLE')),
                ('script_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash del script')),
                ('generation_status', models.CharField(choices=[('S', 'Success'), ('E', 'Error')], default='S', max_length=1, verbose_name='Resultado de generación')),
                ('error_message', models.CharField(blank=True, default='', max_length=300, verbose_name='Mensaje de error')),
                ('is_current', models.BooleanField(default=False, verbose_name='Versión vigente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_versions', to='maintenance_builder.maintenancedefinition', verbose_name='Mantenimiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Versión de script',
                'verbose_name_plural': 'Versiones de script',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSourceSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('role_code', models.CharField(choices=[('BASE_DSPF', 'Base DSPF'), ('BASE_SQLRPGLE', 'Base SQLRPGLE')], max_length=14, verbose_name='Rol')),
                ('source_type_expected', models.CharField(max_length=20, verbose_name='Tipo esperado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_selections', to='maintenance_builder.maintenancedefinition', verbose_name='Mantenimiento')),
                ('source_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_source_selections', to='sources.sourcetemplate', verbose_name='Plantilla fuente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Selección de plantilla',
                'verbose_name_plural': 'Selecciones de plantilla',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSpSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('operation', models.CharField(choices=[('READ_C', 'READ-C'), ('ADD', 'ADD'), ('READ_R', 'READ-R'), ('UPD', 'UPD'), ('DLT', 'DLT')], max_length=6, verbose_name='Operación')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('selection_status', models.CharField(choices=[('S', 'Seleccionado'), ('N', 'No seleccionado')], default='N', max_length=1, verbose_name='Estado de selección')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_selections', to='maintenance_builder.maintenancedefinition', verbose_name='Mantenimiento')),
                ('sp_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_sp_selections', to='sp_asistido.spdefinition', verbose_name='SP seleccionado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Selección de SP',
                'verbose_name_plural': 'Selecciones de SP',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStepState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('step_number', models.PositiveSmallIntegerField(verbose_name='Paso')),
                ('payload_json', models.JSONField(verbose_name='Payload')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Paso completado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_states', to='maintenance_builder.maintenancedefinition', verbose_name='Mantenimiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Estado de paso',
                'verbose_name_plural': 'Estados de paso',
            },
        ),
        migrations.AddIndex(
            model_name='maintenancedefinition',
            index=models.Index(fields=['company', 'status'], name='maintenance_company_0f7ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancedefinition',
            index=models.Index(fields=['company', 'name_short'], name='maintenance_company_e74052_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancedefinition',
            constraint=models.UniqueConstraint(fields=('company', 'name_short'), name='uq_maintenance_builder_company_name_short'),
        ),
        migrations.AddConstraint(
            model_name='maintenancescriptversion',
            constraint=models.UniqueConstraint(fields=('maintenance', 'version'), name='uq_maintenance_builder_script_version_number'),
        ),
        migrations.AddConstraint(
            model_name='maintenancescriptversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('maintenance',), name='uq_maintenance_builder_single_current_script'),
        ),
        migrations.AddConstraint(
            model_name='maintenancesourceselection',
            constraint=models.UniqueConstraint(fields=('maintenance', 'role_code'), name='uq_maintenance_builder_source_selection_role'),
        ),
        migrations.AddConstraint(
            model_name='maintenancespselection',
            constraint=models.UniqueConstraint(fields=('maintenance', 'operation'), name='uq_maintenance_builder_sp_selection_operation'),
        ),
        migrations.AddConstraint(
            model_name='maintenancestepstate',
            constraint=models.UniqueConstraint(fields=('maintenance', 'step_number'), name='uq_maintenance_builder_step_state_per_step'),
        ),
    ]
