# Generated by Django 6.0.4 on 2026-06-01 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('table_design', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('READ', 'READ (SELECT)'), ('ADD', 'ADD (INSERT)'), ('UPD', 'UPD (UPDATE)'), ('DLT', 'DLT (DELETE)')], max_length=4, verbose_name='Operación')),
                ('read_mode', models.CharField(choices=[('C', 'READ-C (cursor)'), ('R', 'READ-R (registro único)')], default='C', max_length=1, verbose_name='Modalidad READ')),
                ('read_row_policy', models.CharField(choices=[('E', 'Error si devuelve más de uno'), ('F', 'Tomar primer registro')], default='E', max_length=1, verbose_name='Política READ-R (múltiples filas)')),
                ('schema_name', models.CharField(max_length=10, verbose_name='Esquema / librería del SP')),
                ('procedure_name_short', models.CharField(max_length=10, verbose_name='Nombre corto del SP')),
                ('procedure_name_long', models.CharField(max_length=50, verbose_name='Nombre largo (descriptivo)')),
                ('procedure_comment', models.CharField(blank=True, default='', max_length=200, verbose_name='Comentario descriptivo')),
                ('status', models.CharField(choices=[('D', 'Borrador'), ('A', 'Activo'), ('I', 'Inactivo')], default='D', max_length=1, verbose_name='Estado de la definición')),
                ('current_step', models.PositiveSmallIntegerField(default=1, verbose_name='Paso actual del wizard')),
                ('script_generated', models.BooleanField(default=False, verbose_name='Script generado')),
                ('script_date', models.DateField(blank=True, null=True, verbose_name='Fecha de script')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sp_definitions', to='company.company', verbose_name='Compañía')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_asistido_definitions_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('header_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sp_definitions', to='table_design.headertable', verbose_name='Tabla diseño (cabecera)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_asistido_definitions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Definición SP asistido',
                'verbose_name_plural': 'Definiciones SP asistido',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SPCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_kind', models.CharField(choices=[('WHERE', 'WHERE'), ('ORDER', 'ORDER BY'), ('FETCH', 'FETCH / paginación')], max_length=10, verbose_name='Tipo de cláusula')),
                ('operator', models.CharField(blank=True, default='', max_length=12, verbose_name='Operador SQL')),
                ('value_origin', models.CharField(blank=True, choices=[('IN', 'Parámetro IN'), ('LITERAL', 'Literal'), ('EXPR', 'Expresión SQL'), ('NULL', 'NULL / IS NULL')], default='', max_length=10, verbose_name='Origen del valor')),
                ('value_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Valor o nombre de parámetro')),
                ('logical_join', models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], default='', max_length=3, verbose_name='Unión con siguiente condición')),
                ('ordinal', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_asistido_conditions_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('detail_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sp_asistido_conditions', to='table_design.detailtable', verbose_name='Campo detalle')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_asistido_conditions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('sp_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='sp_asistido.spdefinition', verbose_name='Definición SP')),
            ],
            options={
                'verbose_name': 'Condición SP (WHERE/ORDER/FETCH)',
                'verbose_name_plural': 'Condiciones SP (WHERE/ORDER/FETCH)',
                'ordering': ['sp_definition_id', 'ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SPAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('IN', 'Parámetro IN'), ('LITERAL', 'Literal'), ('NULL', 'NULL'), ('EXPR', 'Expresión SQL')], max_length=10, verbose_name='Origen del valor')),
                ('source_value', models.CharField(blank=True, default='', max_length=255, verbose_name='Detalle (literal, nombre IN, expresión)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_asistido_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('detail_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sp_asistido_assignments', to='table_design.detailtable', verbose_name='Campo detalle')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_asistido_assignments_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('sp_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sp_asistido.spdefinition', verbose_name='Definición SP')),
            ],
            options={
                'verbose_name': 'Asignación columna (SET/INSERT)',
                'verbose_name_plural': 'Asignaciones columna (SET/INSERT)',
            },
        ),
        migrations.CreateModel(
            name='SPArtifactVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Número de versión')),
                ('sql_script', models.TextField(verbose_name='Script SQL')),
                ('script_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Huella del script')),
                ('is_current', models.BooleanField(default=False, verbose_name='Versión vigente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_asistido_artifact_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_asistido_artifact_versions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('sp_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_versions', to='sp_asistido.spdefinition', verbose_name='Definición SP')),
            ],
            options={
                'verbose_name': 'Versión de artefacto SQL',
                'verbose_name_plural': 'Versiones de artefacto SQL',
                'ordering': ['sp_definition_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='SPParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3, verbose_name='Dirección')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre del parámetro')),
                ('db2_type', models.CharField(max_length=50, verbose_name='Tipo DB2 / SQL')),
                ('ordinal', models.PositiveSmallIntegerField(verbose_name='Orden en la firma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_asistido_parameters_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('sp_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='sp_asistido.spdefinition', verbose_name='Definición SP')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_asistido_parameters_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Parámetro SP',
                'verbose_name_plural': 'Parámetros SP',
                'ordering': ['sp_definition_id', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='SPStepState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(verbose_name='Número de paso')),
                ('payload_json', models.JSONField(verbose_name='Payload del paso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_asistido_step_states_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('sp_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_states', to='sp_asistido.spdefinition', verbose_name='Definición SP')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_asistido_step_states_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Estado de paso (wizard)',
                'verbose_name_plural': 'Estados de paso (wizard)',
            },
        ),
        migrations.AddIndex(
            model_name='spdefinition',
            index=models.Index(fields=['company', 'operation'], name='sp_asistido_company_d5c084_idx'),
        ),
        migrations.AddIndex(
            model_name='spdefinition',
            index=models.Index(fields=['company', '-updated_at'], name='sp_asistido_company_ea850a_idx'),
        ),
        migrations.AddConstraint(
            model_name='spartifactversion',
            constraint=models.UniqueConstraint(fields=('sp_definition', 'version'), name='uq_sp_asistido_artifactversion_definition_version'),
        ),
        migrations.AddConstraint(
            model_name='spparameter',
            constraint=models.UniqueConstraint(fields=('sp_definition', 'name'), name='uq_sp_asistido_parameter_definition_name'),
        ),
        migrations.AddConstraint(
            model_name='spstepstate',
            constraint=models.UniqueConstraint(fields=('sp_definition', 'step_number'), name='uq_sp_asistido_stepstate_definition_step'),
        ),
    ]
