# Generated by Django 6.0.4 on 2026-06-01 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('document_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento de identidad')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('user_type', models.CharField(choices=[('SU', 'Super usuario'), ('AC', 'Administrador de compañía'), ('AS', 'Administrador de sistema'), ('US', 'Usuario')], default='US', max_length=2, verbose_name='Tipo de usuario')),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
                ('totp_secret', models.CharField(blank=True, max_length=64, null=True, verbose_name='Secreto TOTP')),
                ('tfa_verified', models.BooleanField(default=False, verbose_name='2FA verificado')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Email confirmado')),
                ('email_confirm_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de confirmación')),
                ('email_confirm_exp', models.DateTimeField(blank=True, null=True, verbose_name='Expiración del código')),
                ('last_totp_reset', models.DateTimeField(blank=True, null=True, verbose_name='Último reset de TOTP')),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='Último cambio de contraseña')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='company.company', verbose_name='Compañía')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'ordering': ['user__username'],
            },
        ),
    ]
